### ISSUE TITLE
'more like this' link in HUD often shows zero results

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/test-infra#1069]
This is especially prominent on test failures, where there's a failing test but when you click "more like this" it takes you to a page with zero matching hits

Example:
The test failure [here](https://hud.pytorch.org/pytorch/pytorch/commit/396c3b1d88d7624938a2bb0b287f2a19f1e89bb4) leads to [this page](https://hud.pytorch.org/failure/test_dispatch_meta_outplace_fft_ifft_cuda_float64%2CTestMetaCUDA) which shows no results, not even the result on the test itself

![Image](https://user-images.githubusercontent.com/4468967/201390696-a70e5662-6dbe-4956-b3a1-b6787f43934f.png)

If the above example is more than two weeks old, you can find a more recent example by looking for tests which have flaked and failed.

**Comment by huydhn** [comment]
The feature also doesn't work for pytest test_ops, i.e. https://hud.pytorch.org/pytorch/pytorch/commit/cbdb683dc843f2d50617ad962d5e57501e5154d4 or https://hud.pytorch.org/failure/FAILED%20test_ops.py%3A%3ATestCommonCUDA%3A%3Atest_python_ref_executor__refs_sin_executor_nvfuser_cuda_int32%20-%20RuntimeError%3A%20CUDA%20driver%20error%3A%20invalid%20resource%20handle.  It looks like we would need a better text search capability here eventually

**Comment by clee2000** [comment]
should be fixed by https://github.com/pytorch/test-infra/pull/1220
