### ISSUE TITLE
Investigate why github-status-webhook-handler are loosing notifications again

### ISSUE THREAD

**Issue by malfet** [pytorch/test-infra#125]
Have a look at this one for example
![image](https://user-images.githubusercontent.com/2453524/134410977-030a8a1c-0e38-4ee5-b915-889fafd1b2a1.png)
[test (distributed, 1, 1, linux.2xlarge)](https://github.com/pytorch/pytorch/runs/3668213067) has completed, and is marked as such in this commit https://github.com/pytorch/pytorch/commit/73c4bfc30aa9a425fb5b565839f96779bd0aae6a
but according to https://s3.amazonaws.com/ossci-job-status/master/73c4bfc30aa9a425fb5b565839f96779bd0aae6a.json it is still pending

**Comment by driazati** [comment]
just flagging again that the combination of #112 and https://github.com/pytorch/pytorch-ci-hud/pull/132 would work around these issues, for example right now this is hud.pytorch.org:

![image](https://user-images.githubusercontent.com/9407960/135379187-9932db25-e977-4656-9adb-d9dcf7e814a7.png)

and this is the preview of https://github.com/pytorch/pytorch-ci-hud/pull/132 at https://deploy-preview-132--pytorch-ci-hud.netlify.app/build3/pytorch-master

![image](https://user-images.githubusercontent.com/9407960/135379223-7b4cee65-1b7b-4881-b16a-f1f25fce61d3.png)
