### ISSUE TITLE
Cancelled Docker build jobs are confusing

### ISSUE THREAD

**Issue by ezyang** [pytorch/test-infra#1335]
In https://hud.pytorch.org/pytorch/pytorch/pull/83816?sha=adb0c6fd4b37eef4ca2e7dd28f4954e82e16ea94 there are a bunch of docker jobs that are cancelled. It is weird and unexplained and you might think it is an infra problem. But in fact, the problem is that  one docker build failed and cancelled all the other ones. You have to know that and look at the particular problem.

Some possible fixes:
* Don't show cancelled builds in HUD
* Let docker jobs run to completion, don't cancel on the first failure

**Comment by clee2000** [comment]
fixed by https://github.com/pytorch/pytorch/pull/92816?
