### ISSUE TITLE
Figure out some solution for codev PRs that fail trunk. Today they get force merged and break trunk

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/test-infra#1380]
Re: Prioritization, given that we rarely see codev PRs that need to be reverted (maybe seeing one ever 1-2 months) and have more impactful changes that can be made, this can be considered lower pri right now

**Comment by clee2000** [comment]
https://github.com/pytorch/pytorch/pull/98010 is a case of this, PR got merged internally without trunk signal, but trunk was red

**Comment by clee2000** [comment]
I believe this gets fixed by https://github.com/pytorch/test-infra/pull/4810 by @PaliC (add ciflow/trunk on review for codev PRs)
