### ISSUE TITLE
Conda release should remove the older packages from the nightly channel

### ISSUE THREAD

**Issue by ejguan** [pytorch/test-infra#1413]
The currently implementation only does the [upload](https://github.com/pytorch/test-infra/blob/94979f5abb35c9b4b1a5201d5fe7cc6863659945/.github/workflows/build_conda_linux.yml#L190-L200).
So, all the older packages are still stored in `pytorch-nightly` channel. At the end, it blows up the storage limit on conda.
See failed workflow:
- TorchText: https://github.com/pytorch/text/actions/runs/3939245779/jobs/6738891206#step:12:183
- TorchData: https://github.com/pytorch/data/actions/runs/3948240115/jobs/6758525347#step:6:259
Note: This problem only happens for nightly releases

For reference, this is how TorchData achieves removing the old packages and uploading the new packages based on python version and platform.
https://github.com/pytorch/data/blob/38e0d03454a9018cb7ebf76e6b31379db913f8a1/.github/workflows/_build_test_upload.yml#L413-L437

**Comment by weiwangmeta** [comment]
https://github.com/pytorch/pytorch/pull/93876 included torchtext for periodic clean up. 
I will add torchdata.
