### ISSUE TITLE
Bot sends false positive alerts

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#1422]
These issues are reported by Nikita when looking into the `inductor_huggingface` alert in https://github.com/pytorch/test-infra/issues/1418#issuecomment-1397812502.

* [ ] Alert is triggered when red signals arrived out of order with green signal(s) in between

There were 2 failures on [HUD](https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=inductor_huggingface) responsible for this alert but they weren't consecutive and arrived out of order with a green signal in between
* https://github.com/pytorch/pytorch/commit/190f7803f5d90d027f331eaf48ef5fa63f14737a (FAILED - 1 red signal)
* https://github.com/pytorch/pytorch/commit/550983e39dd290d95c0d6327d52cd5cfe6497be8 (OK - 3 green signal)
* https://github.com/pytorch/pytorch/commit/60bf851931f58e528be927d96115272248f531fd (FAILED - 2 red signal)

* [ ] Alert is triggered when a job fails with not even the same failures.  This is counted as flaky, not broken trunk.  We might or might not need alert for this.  In the above example, both red signals were due to different reasons

cc @malfet @ZainRizvi @clee2000 @pytorch/pytorch-dev-infra

**Comment by ZainRizvi** [comment]
1. What does "arrived out of order" mean in this case? That rockset returned the data in the wrong order (it wasn't sorted) or that the jobs completed in a different order (which is normal if a newer job fails early)? ...I assume the latter
2. Yeah, we should def fix the alerting when the jobs fail with different failures. Taking care of this issue would implicitly fix the first, and denoise our alerts as well

**Comment by huydhn** [comment]
> What does "arrived out of order" mean in this case?  It's the latter.  The jobs completed in a different order.  I have noted down the order 1, 2, 3 above

**Comment by ZainRizvi** [comment]
Duped by https://github.com/pytorch/test-infra/issues/1083
