### ISSUE TITLE
Allow for open registration of ciflow/ labels

### ISSUE THREAD

**Issue by ezyang** [pytorch/test-infra#1439]
I shouldn't have to do a bot push to add a new ciflow label. Most of the config is just in the actions

**Comment by malfet** [comment]
To elaborate a bit, have list of valid labels hardcoded in https://github.com/pytorch/test-infra/blob/2c9f126bc39ba59625fb069b84b0f9d0c32cb0fd/torchci/lib/bot/ciflowPushTrigger.ts#L138-L145
feels wrong, it should be part of pytorch-probot.yml in the respective repository (this way, we can also have a check in that repo that all `ciflow/` labels are accounted for

**Comment by malfet** [comment]
First part of the change is to mention them in repo config: https://github.com/pytorch/pytorch/pull/94368
