### ISSUE TITLE
Test disabling bot should include file path for test

### ISSUE THREAD

**Issue by ezyang** [pytorch/test-infra#1440]
Many of our tests have uninformative top level class names, and subdirectory structure means their file name is not that useful either. If you include the test file path like test/dynamo/test_misc.py that goes a long way for saying what the test actually is for triage purposes.

**Comment by malfet** [comment]
Should be closed by https://github.com/pytorch/test-infra/commit/7ca108695c3dc53eaa7ccab5fe470423e297ea3a
