### ISSUE TITLE
Create Alerts in grafana server goes down or generate a lot of Exceptions

### ISSUE THREAD

**Issue by atalman** [pytorch/test-infra#152]
We would need to create alerts to metrics.pytorch.org when the server becomes unreachable for X (5?) minutes or more.
Alerts should be sent to pytorch_dev_infra oncall

**Comment by janeyx99** [comment]
Note: We should discuss this prior to implementing.

**Comment by zengk95** [comment]
closing this since we're migrating to HUD.
