### ISSUE TITLE
[Bot] Add ability to assign "relnotes" labels to PRs by contributors

### ISSUE THREAD

**Issue by malfet** [pytorch/test-infra#190]
See https://github.com/pytorch/pytorch/pull/72372#issuecomment-1030683817

We could probably add functionality to probot to actually allow people to use chatops to apply release notes labels.

Similar to

```
@pytorchbot label {label_name}
```

**Comment by malfet** [comment]
Could be done by either extending https://github.com/pytorch/test-infra/blob/main/torchci/lib/bot/mergeBot.ts or adding a new bot that would react on comments

**Comment by malfet** [comment]
Also, please add a test to https://github.com/pytorch/test-infra/tree/main/torchci/test, similar to https://github.com/pytorch/test-infra/tree/main/torchci/test (and also, make sure to add false positive tests, i.e. that bot does not add labels on malformed commands or that it would not create a new ones)

**Comment by atalman** [comment]
Please use documentation from probot repo https://github.com/probot/probot and enabled GHA endpoints here: https://docs.github.com/en/rest/overview/endpoints-available-for-github-apps

**Comment by atalman** [comment]
I think we already had similar functionality in the archived repo:
https://github.com/pytorch/probot/blob/685042ed7bee3edbda822c13ad379e8b76171d43/src/ciflow-bot.ts#L504

**Comment by vtsyvina** [comment]
Done in #241
