### ISSUE TITLE
Warn users on deprecated labels + add testing

### ISSUE THREAD

**Issue by janeyx99** [pytorch/test-infra#273]
Followup from https://github.com/pytorch/test-infra/pull/272

There are deprecated labels in pytorch/pytorch, specifically all the ciflow ones that aren't {trunk, pull, periodic, lint} (check the repo for when ciflow is still used) as well as the labels that start with `ci/`. We should make a list for these, and then print a message to the PR whenever anyone tries using them.

**Comment by clee2000** [comment]
Edited label descriptions to say if they're deprecated or not, also added the labels that didn't exist but can be used.
