### ISSUE TITLE
Make build status page in HUD load faster

### ISSUE THREAD

**Issue by ezyang** [pytorch/test-infra#345]
Nikita tells me that it waits for all logs to download before rendering; it would be mice if it rendered the summary first and then fetched logs

**Comment by suo** [comment]
It does not do this, raw logs are only downloaded when you open them up.

I did independently feel that the build status page was getting slowpoke, so I made a small optimization here: https://github.com/pytorch/test-infra/commit/2c8fea2f0d91b8d0c008680ef44628613a6d363a

Let me know if it still feels too slow, I'm sure the query could be further optimized.

**Comment by suo** [comment]
For funsies: here is the core query used by that view. Orange is pre-optimization, blue is post-optimization.
<img width="746" alt="image" src="https://user-images.githubusercontent.com/1617424/169713609-e44d1ebd-bf0f-41d8-ac1e-9eb4a6957484.png">

**Comment by suo** [comment]
ima gonna close this but if it's still slow reopen this
