### ISSUE TITLE
Write pytorchbot commands to rockset

### ISSUE THREAD

**Issue by suo** [pytorch/test-infra#347]
For tracking and metrics purposes, we should be writing pytorchbot commands to Rockset. For each invocation of the bot, we should record:
- user
- command
- arguments provided to the command
- success/failure of the command
- id of workflow launched by the command
- url of the comment that issued the command
- id of the comment
- PR that the comment was on

An example where this would be useful: automating our revert tracking.

**Comment by suo** [comment]
For tracking and metrics purposes, we should be writing pytorchbot commands to Rockset. For each invocation of the bot, we should record:
- user
- command
- arguments provided to the command
- success/failure of the command
- id of workflow launched by the command
- url of the comment that issued the command
- id of the comment
- PR that the comment was on

An example where this would be useful: automating our revert tracking.

**Comment by ZainRizvi** [comment]
Completed
