### ISSUE TITLE
HUD should report not just S3 artifacts, but one generated by the workflow

### ISSUE THREAD

**Issue by malfet** [pytorch/test-infra#3492]
For example for https://hud.pytorch.org/pytorch/pytorch/commit/1f7448eeda824de2c15181997f16376803578529 there are no artifacts visible for `linux-binary-manywheel` workflow,
![image](https://user-images.githubusercontent.com/2453524/218587776-3ee10be0-09da-4d88-bd12-7d02a3463b86.png)
 but there are there if one looks at the https://github.com/pytorch/pytorch/actions/runs/4167281249
![image](https://user-images.githubusercontent.com/2453524/218587853-d84c2adc-0a91-4eae-a1a9-f0e31b312311.png)

**Comment by clee2000** [comment]
upload gh artifacts to s3 when workflow finish

**Comment by clee2000** [comment]
I believe this is fixed by https://github.com/pytorch/pytorch/pull/87827 by @huydhn as long as the workflow is in the list in upload-test-stats.yml https://github.com/pytorch/pytorch/blob/72eab5aa4348a27aad60a649c1e8b8abc60a8efc/.github/workflows/upload-test-stats.yml#L5C76-L5C76
