### ISSUE TITLE
Port `pull_request_review` webhook mergebot to use CLI

### ISSUE THREAD

**Issue by suo** [pytorch/test-infra#359]
e.g. the code here https://github.com/pytorch/test-infra/blob/0f3c12d241b69d61c8e8765ad044e78cc5e52728/torchci/lib/bot/mergeBot.ts#L144

Currently only handles merge, and only the old syntax. We should either update it to use the same stuff as the rest of the system or remove this functionality entirely.

**Comment by kit1980** [comment]
A report that pr review functionality is no longer working:
https://github.com/pytorch/pytorch/issues/72749#issuecomment-1192978035

@zengk95 do you know why? The remove PR wasn't merged as I understand.

**Comment by zengk95** [comment]
> A report that pr review functionality is no longer working: [pytorch/pytorch#72749 (comment)](https://github.com/pytorch/pytorch/issues/72749#issuecomment-1192978035)
> 
> @zengk95 do you know why? The remove PR wasn't merged as I understand.

It's using the old syntax so it's missing the "this".

**Comment by zengk95** [comment]
I've put up a PR to port it over here: https://github.com/pytorch/test-infra/pull/480
