### ISSUE TITLE
Unify validation across trymerge workflow and mergebot

### ISSUE THREAD

**Issue by suo** [pytorch/test-infra#361]
We perform validation in inconsistent places. Sometimes we do it in mergebot: https://github.com/pytorch/test-infra/blob/0f3c12d241b69d61c8e8765ad044e78cc5e52728/torchci/lib/bot/mergeBot.ts#L97-L100

Sometimes we do it in the dispatched workflow: https://github.com/pytorch/pytorch/blob/64a01f12adf94b87f8ebfbab0345e8e3576568cc/.github/scripts/trymerge.py#L853-L854

These rules are often inconsistent and/or redundant. For example, we validate revert arguments in both places differently (`--message` would be allowed by the bot, but rejected by the random regex we have in the workflow).

We should put this in one place. That place should be the mergebot, as it has faster latency when responding to user commands.

**Comment by suo** [comment]
@zengk95 any update on this? We should at least fix the revert one mentioned in #416

**Comment by zengk95** [comment]
@suo 
The -c should be required now. I fixed it a bit ago. I'll work on migrating some of the other checks to the merge bot 
<img width="896" alt="image" src="https://user-images.githubusercontent.com/34172846/175343218-b4eaed9b-0ecb-41c8-bfe7-38fc7ad4694a.png">

**Comment by suo** [comment]
saw an issue again where the the command is valid per the bot, but got rejected by the workflow 
 https://github.com/pytorch/pytorch/pull/78439#issuecomment-1171666882

**Comment by ZainRizvi** [comment]
Fixed by the above PR
