### ISSUE TITLE
mergebot crashing / looping when help message is displayed

### ISSUE THREAD

**Issue by seemethere** [pytorch/test-infra#367]
See https://github.com/pytorch/pytorch/pull/78671

**Comment by seemethere** [comment]
Original comment was said to be `@pytorchbot merge this please`

**Comment by seemethere** [comment]
Potentially related to
* https://github.com/pytorch/test-infra/pull/364
* https://github.com/pytorch/test-infra/pull/358

**Comment by suo** [comment]
looking

**Comment by suo** [comment]
hotfixed https://github.com/pytorch/test-infra/commit/e5e8f8a38017e21a38e235d1d1f4024c3c479523

will followup with something nicer

**Comment by seemethere** [comment]
Closing with https://github.com/pytorch/test-infra/commit/e5e8f8a38017e21a38e235d1d1f4024c3c479523
