### ISSUE TITLE
Embedded log view should strip control characters

### ISSUE THREAD

**Issue by ezyang** [pytorch/test-infra#375]
Whenever I try to copy paste a filename from the log view OS X warns me that the paste has control characters. We just shouldn't have them in the paste.

**Comment by suo** [comment]
@zengk95 do you want to look into this one?

**Comment by zengk95** [comment]
Do you have an example of this? I've tried copying a few things and it seems fine to me. @ezyang

**Comment by ezyang** [comment]
Try copying paths from a failed lintrunner on OSX from Chrome

**Comment by suo** [comment]
This will happen wherever there are colors, as those use ansi escape codes. The raw logs served by github just leave them in, so we need to strip them from whatever we send to the user's clipboard.
