### ISSUE TITLE
Create new model performance dashboards for TorchDynamo on HUD

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#3783]
This is a feature request from dynamo team to have better dashboards to track the performance of different backends.  The current process as described in https://github.com/pytorch/pytorch/issues/93794 is cumbersome in which test artifacts are downloaded to a local dev server, and perf charts are generated manually.

![331538894_694815312385894_8140799468527070148_n](https://user-images.githubusercontent.com/475357/219799354-3c7f0e7e-2d34-41d2-88f4-2c06a3bd3224.png)

The proposed workflow would be to get the data to S3, get Rockset to consume it, then create new pages or integrate with existing pages.

cc @desertfire @weiwangmeta @pytorch/pytorch-dev-infra

**Comment by desertfire** [comment]
cc @gchanan @ezyang @ngimel @penguinwu

**Comment by huydhn** [comment]
Resolve this old issue as the dashboard has been rolled out for a while and there are other tracking issues.
