### ISSUE TITLE
[Flaky tests] Stress test on flaky test issue close

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/test-infra#379]
When a flaky test issue such as https://github.com/pytorch/pytorch/issues/78768 is closed in CI, the test is re-enabled (and hopefully fixed).

However, it could be possible that the test is still flaky despite a fix and the developer's best intentions to test their fix.

To accomodate for this, could PyTorch CI automatically "stress test" when re-enabling disabled tests (similar to sandcastle)?

For example, run the particular test say 100 times for the next 10 commits into PyTorch master. This would help a lot with confidence that the issue is fixed, or it would quickly give the developer feedback that the test was actually not fixed.

cc @janeyx99 @suo

**Comment by huydhn** [comment]
Resolving this issue as rerunning disabled has now been part of the CI.  Basically, a disabled flaky test would be running multiple times daily and would only be marked as fixed once it's not flaky anymore in the period of 2 weeks (100% success)
