### ISSUE TITLE
Getting pytorch-probot.yml from PR instead of trunk when running in PR context

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#3849]
Per convo in https://github.com/pytorch/pytorch/pull/96166#issuecomment-1458710080

@malfet I create this issue for spring planning today

**Comment by huydhn** [comment]
Not a high priority issue. There are work around like pushing the tag manually.

**Comment by PaliC** [comment]
- Do a quick check for write access otherwise use trunk.
- Just allow creating a new label, and then just do the check + have a warning. (Does not apply to first time contributors)
