### ISSUE TITLE
Unify HUD and docs preview paths?

### ISSUE THREAD

**Issue by pmeier** [pytorch/test-infra#3894]
We just enabled docs preview on TorchVision by uploading it to docs-preview.pytorch.org. However, we noticed that the paths diverge from the ones used by the HUD. #3891 was a quick fix to get it up and running, but we should have a discussion around unifying this.

## HUD

- https://hud.pytorch.org/hud/pytorch/pytorch/master
- https://hud.pytorch.org/hud/pytorch/pytorch/nightly
- https://hud.pytorch.org/hud/pytorch/vision/main
- https://hud.pytorch.org/hud/pytorch/audio/main

scheme: `https://hud.pytorch.org/hud/$OWNER/$REPO/$BRANCH`

## HUD linked from bot PR comments

- https://hud.pytorch.org/pr/96954 (this is what the bot comments, but it seems to be shortcut for the link below)
- https://hud.pytorch.org/pr/pytorch/pytorch/96131
- https://hud.pytorch.org/pr/pytorch/vision/7427

scheme: `https://hud.pytorch.org/pr/$OWNER/$REPO/$PR`

## Doc preview linked from bot comments

- https://docs-preview.pytorch.org/96131/index.html
- https://docs-preview.pytorch.org/96131/cppdocs/index.html
- https://docs-preview.pytorch.org/vision/7427/index.html

There is no unifying scheme. PyTorch core uses `https://docs-preview.pytorch.org/$PR/index.html` whereas TorchVision uses `https://docs-preview.pytorch.org/$REPO/$PR/index.html`. Both diverge from the HUD links in the sense that `$OWNER` is never used.

## Proposal

Docs preview should be served under `https://docs-preview.pytorch.org/$OWNER/$REPO/$PR/index.html` to align with the HUD links. This should not break any pre-existing links, since the proposed scheme can coexist with the old one.

**Comment by seemethere** [comment]
I'd +1 the `${OWNER}/${REPO}/${PR}/index.html` scheme for docs-previews.

Would also be good if we ever decided to branch out support to different organizations like facebookresearch

**Comment by pmeier** [comment]
While looking into this, I figured that [`seemethere/upload-artifact-s3`](https://github.com/seemethere/upload-artifact-s3) is swallowing the `${OWNER}` part of the link. In PyTorch core we use [`pytorch/$PR`](https://github.com/pytorch/pytorch/blob/62eb7a2e97205cad35ae7acd02a6bbf835db341f/.github/workflows/_docs.yml#L160) and that gets uploaded to `https://docs-preview.pytorch.org/$PR`. On TorchVision we use [`pytorch/vision/$PR`](https://github.com/pytorch/vision/blob/b403bfc771e0caf31efd06d43860b09004f4ac61/.github/workflows/docs.yml#L68) and it gets uploaded to `https://docs-preview.pytorch.org/vision/$PR`.

**Comment by seemethere** [comment]
> While looking into this, I figured that [`seemethere/upload-artifact-s3`](https://github.com/seemethere/upload-artifact-s3) is swallowing the `${OWNER}` part of the link. In PyTorch core we use [`pytorch/$PR`](https://github.com/pytorch/pytorch/blob/62eb7a2e97205cad35ae7acd02a6bbf835db341f/.github/workflows/_docs.yml#L160) and that gets uploaded to `https://docs-preview.pytorch.org/$PR`. On TorchVision we use [`pytorch/vision/$PR`](https://github.com/pytorch/vision/blob/b403bfc771e0caf31efd06d43860b09004f4ac61/.github/workflows/docs.yml#L68) and it gets uploaded to `https://docs-preview.pytorch.org/vision/$PR`.

We'd need to switch core over first before I can switch the cloudfront distribution to use `/` as the root but I'd generally be fine with doing it that way.

**Comment by pmeier** [comment]
So maybe switch PyTorch core to `pytorch/$OWNER/$REPO/$PR` and drop the `pytorch/` afterwards as simultaneous as possible?

**Comment by seemethere** [comment]
> So maybe switch PyTorch core to `pytorch/$OWNER/$REPO/$PR` and drop the `pytorch/` afterwards as simultaneous as possible?

Yup that'd be the idea
