### ISSUE TITLE
mergebot should comment again when the merge is complete

### ISSUE THREAD

**Issue by suo** [pytorch/test-infra#392]
Right now, if I enqueue a merge, the mergebot comments that a merge is progress. It should comment again when the merge is complete, with a commit link (and maybe a link to the HUD as well).

Technically the merge shows up in the timeline already so this information is slightly redundant, but:
- A comment will trigger a notification (and an email), which is nice.
- A comment gives us the opportunity to add extra info (like the HUD link).
- I think it makes the UX more consistent—every change in the PR's merge state machine should have a corresponding bot comment. It feels slightly weird for the bot to tell me something is in progress and then not tell me when it's done.

**Comment by suo** [comment]
@zengk95, @janeyx99  what do you think?

**Comment by janeyx99** [comment]
I agree with this. The rule of "every state change should have a corresponding bot comment" is something we should try to uphold when developing UX

**Comment by zengk95** [comment]
Sounds good. Will add it
