### ISSUE TITLE
Add/remove a 'merging' label when a bot land is in progress

### ISSUE THREAD

**Issue by ezyang** [pytorch/test-infra#3950]
I frequently have a bunch of PRs that I need to nanny and see if they failed merging one way or another. I can use https://github.com/pulls to quickly review said PRs, but I cannot easily tell if it is merging or not. If pytorchbot maintained a label merging which it added when a PR was in the process of merging, and removed if it failed to merge, that would be a big help.

**Comment by malfet** [comment]
One can do something like that, but the danger here, if mergebot dies for some reason, `merging` label would not be removed.

**Comment by PaliC** [comment]
Add removal on the cancel workflow
- possible race condition when creating new workflow (causes old one to cancel)

**Comment by PaliC** [comment]
Closed by https://github.com/pytorch/pytorch/pull/98543
