### ISSUE TITLE
nvJPEG is missing from Windows GPU runners

### ISSUE THREAD

**Issue by pmeier** [pytorch/test-infra#3979]
According to the [NVIDIA website](https://developer.nvidia.com/nvjpeg), nvJPEG should come with the CUDA installation:

> * For the most current version of nvJPEG, download the [CUDA Toolkit](https://developer.nvidia.com/cuda-toolkit).
> * If you are using CUDA Toolkit 10.0 or 9.0, please download the [nvJPEG installer](https://developer.nvidia.com/nvjpeg-release-download).

However, this does not seem to be the case: https://github.com/pytorch/vision/actions/runs/4594756756/jobs/8114184733#step:9:234

The images `torchvision` uses for CircleCI have an explicit check for this: https://github.com/pytorch/vision/blob/781f512b01bc2324d7fdd11f0901f60571fc476f/.circleci/unittest/windows/scripts/set_cuda_envs.sh#L32-L35 Doing the same on the `windows_job`, fails (pytorch/vision#7475)

This currently blocks migrating Windows GPU workflows for `torchvision`.

**Comment by malfet** [comment]
CUDA installer can choose whether or not to include various subcomponents and I had to fix missing nvjpeg in torchvision many times, most recent in https://github.com/pytorch/vision/pull/7186

I.e. looks like all one has to do is to add nvjpeg to https://github.com/pytorch/test-infra/blob/2fec0c947e7f761e8e37304ab45245c2067ffab8/aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1#L13 and the deploy new AMI. @atalman can you please take care of that?

**Comment by pmeier** [comment]
Why do we install only parts of the toolkit and not all of it? Is storage on the runners a concern? If yes, I saw that there are older versions, i.e. < CUDA 11.7, present on the runner that could potentially be removed.

**Comment by atalman** [comment]
this is completed AMI was deployed
