### ISSUE TITLE
merge -f should require a reason

### ISSUE THREAD

**Issue by janeyx99** [pytorch/test-infra#409]
As more people use this flag, we should track the usage + why people may be resorting to it

This would also serve as an additional safeguard as f and g are close on the keyboard

**Comment by huydhn** [comment]
I have created a new Rockset query lambda [force_push](https://console.rockset.com/lambdas/details/commons.force_push?tab=summary) to track this (who do what). https://github.com/pytorch/pytorch/pull/81582 has the honor to be  the first record 🥇

**Comment by janeyx99** [comment]
@huydhn Is this landed already/should we close this PR or is it still in beta stages?

Also, could you please update our bot wiki with the new generated help command + instructions? https://github.com/pytorch/pytorch/wiki/Bot-commands

**Comment by huydhn** [comment]
Got it, I forgot to close this one. I will do it now and update the wiki accordingly
