### ISSUE TITLE
[feature]: Bash script to run failing tests locally

### ISSUE THREAD

**Issue by tfsingh** [pytorch/test-infra#4091]
I think it would be nice if one could download/copy an automatically generated bash script from the HUD that executes only the specific tests they are failing. This would enable developers in being able to quickly test their code, rather than having to manually execute individual tests or run the entire suite. There might be an existing way of doing this, but if not, I'd happily implement this.

**Comment by huydhn** [comment]
cc @ZainRizvi @clee2000 @kit1980 @huydhn

**Comment by tfsingh** [comment]
Thank you @huydhn , would just like to reiterate that I'd be more than happy to work on this.

**Comment by ZainRizvi** [comment]
@tfsingh you're welcome to submit a PR against this task!

**Comment by tfsingh** [comment]
Sounds great, I'll likely ask some questions about what yourself/the devX team would like the UX for this operation to look like once I dive into the code for the HUD.

**Comment by ZainRizvi** [comment]
Sure thing. Feel free to ask questions here, or to come to our office hours on Friday: https://github.com/pytorch/pytorch/wiki/Dev-Infra-Office-Hours
