### ISSUE TITLE
CI failed but merge bot let it through anyway

### ISSUE THREAD

**Issue by ezyang** [pytorch/test-infra#4126]
https://github.com/pytorch/pytorch/pull/100369

If you look at the HUD, the XLA job is clearly failing, but somehow a merge let it through anyway

**Comment by malfet** [comment]
It should have checked those signals:
https://github.com/pytorch/pytorch/blob/86ddfc7f68fa598bdc392e7eb90b66c412a7ffad/.github/merge_rules.yaml#L88

**Comment by malfet** [comment]
@huydhn as you've added this logic, do you mind having a look at it?
From my layman's observation, XLA was not flaky at the time of merge, see https://hud.pytorch.org/hud/pytorch/pytorch/main/1?per_page=50&name_filter=xla%2C
<img width="852" alt="image" src="https://user-images.githubusercontent.com/2453524/236872823-97af8a73-e355-4261-a344-9b73985db949.png">

**Comment by huydhn** [comment]
I think we have an FP in flakiness rule here https://github.com/pytorch/test-infra/blob/generated-stats/stats/flaky-rules.json#L10-L13.   The bot checked this file and wrongly assumed that XLA failure was flaky and ignore it.  I will remove this rule first and check with @clee2000  if there is a more flexible way to implement this flakiness check.

The FP rule looks as follows:

```
  { 
    "name": "-xla",
    "captures": ["FAILED: Build did NOT complete successfully"]
  },
```

and it matches the failure in the hash update PR https://hud.pytorch.org/pr/pytorch/pytorch/100369#13305922042

**Comment by ZainRizvi** [comment]
Something related, mergebot also thought this lint failure was from a broken trunk when this PR was the one that actually introduced it

Look at Dr.CI's comment history to see it being classified as a broken trunk error
https://github.com/pytorch/pytorch/pull/100661#issuecomment-1535441021
