### ISSUE TITLE
Copy link to page in compiler hud does not prepend http://

### ISSUE THREAD

**Issue by ezyang** [pytorch/test-infra#4137]
you get `hud.pytorch.org/benchmark/torchbench/inductor_dynamic?startTime=Tue%2C%2002%20May%202023%2001%3A44%3A33%20GMT&stopTime=Tue%2C%2009%20May%202023%2001%3A44%3A33%20GMT&mode=training&dtype=amp&lBranch=main&lCommit=970c60b336b7bc346cd1cbb8b86f547983c9668a&rBranch=main&rCommit=55b661137f0c162968592bead66598fe4b091ce8` by default (no protocol)

**Comment by huydhn** [comment]
Fixed by https://github.com/pytorch/test-infra/pull/4235
