### ISSUE TITLE
Cant View Inference Run on PT2 Dash

### ISSUE THREAD

**Issue by eellison** [pytorch/test-infra#4186]
![image](https://github.com/pytorch/test-infra/assets/11477974/88b8f78d-2323-445a-a8b2-0991a67b5bdd)

**Comment by desertfire** [comment]
@huydhn , this is caused by a recent reduction of inference benchmarking frequency. We need to select the exact two commits with inference run as before/after for inference result to show up. We should use before/after as a range and show all inference data points in between.

**Comment by ezyang** [comment]
This is still broken!

**Comment by huydhn** [comment]
Fixed by https://github.com/pytorch/test-infra/pull/4235
