### ISSUE TITLE
Something wrong with geomean computation?

### ISSUE THREAD

**Issue by ezyang** [pytorch/test-infra#4196]
https://hud.pytorch.org/benchmark/compilers?startTime=Mon%2C%2015%20May%202023%2017%3A09%3A51%20GMT&stopTime=Mon%2C%2022%20May%202023%2017%3A09%3A51%20GMT&suite=torchbench&mode=inference&dtype=amp&lBranch=main&lCommit=351c2ea2fbb09add93980e2942435f31b114047c&rBranch=main&rCommit=f994d0b619d4643af24b4c49672e534fec729024

The summary says

<img width="344" alt="image" src="https://github.com/pytorch/test-infra/assets/13564/0d3c3fa3-2d53-4546-9b57-a275842ca13f">

But when I look at the data nearly all of the data points got worse

https://hud.pytorch.org/benchmark/torchbench/inductor_with_cudagraphs?startTime=Mon,%2015%20May%202023%2017:09:51%20GMT&stopTime=Mon,%2022%20May%202023%2017:09:51%20GMT&mode=inference&dtype=amp&lBranch=main&lCommit=351c2ea2fbb09add93980e2942435f31b114047c&rBranch=main&rCommit=f994d0b619d4643af24b4c49672e534fec729024

<img width="855" alt="image" src="https://github.com/pytorch/test-infra/assets/13564/7d0118d1-523c-4f3c-bccf-d98177fc931a">

How did we compute the geomean?

**Comment by huydhn** [comment]
Here is how the value is calculated https://github.com/pytorch/test-infra/blob/main/torchci/pages/benchmark/compilers.tsx#L225-L235.  I suspect that some models were run and got 0 speedup there, thus they were excluded from the calculation

**Comment by ezyang** [comment]
If that were the case I'd expect some 0 -> blah transitions (or vice versa), but none seem to be printed

**Comment by kit1980** [comment]
I wonder if there is a left/right bug somewhere similar to https://github.com/pytorch/test-infra/issues/4197 (although that bug in particular looks like a purely UI issue).

**Comment by ezyang** [comment]
Another example https://hud.pytorch.org/benchmark/torchbench/inductor_with_cudagraphs?startTime=Tue,%2016%20May%202023%2015:24:09%20GMT&stopTime=Tue,%2023%20May%202023%2015:24:09%20GMT&mode=training&dtype=amp&lBranch=main&lCommit=b91eb97d34536dbdf22bbf7555a8e64ca7932c51&rBranch=main&rCommit=e9a7115605ee5b6ae38ea5716a4abea5aa415333 shows no change in peak memory compression ratio, but the summary says there was a .01 difference.

**Comment by huydhn** [comment]
For the 1st issue, I have double checked the calculation on HUD, with my own Python script, and online tools like http://www.alcula.com/calculators/statistics/geometric-mean/, and the calculation looks correct.

The older commit f994d0b619d4643af24b4c49672e534fec729024 had geomean speedup of `1.4915172412148` using the following raw data `[1.400085, 1.494902, 2.501723, 1.300856, 1.375717, 1.249006, 1.158561, 1.861724, 1.332822, 4.181205, 3.470274, 0, 1.054895, 1.197184, 1.734711, 0, 2.026529, 1.383986, 1.186607, 3.486375, 1.402958, 1.225394, 3.552801, 2.042867, 1.447406, 1.998685, 2.151968, 1.90649, 1.417369, 1.765423, 2.393887, 1.34081, 1.939297, 1.691439, 0, 2.038128, 1.923072, 1.321604, 0.000805, 3.82697, 1.52481, 1.54917, 1.454324, 0, 0, 0.868344, 0.64118, 2.358431, 1.748372, 11.462144, 1.270221, 3.540724, 1.805148, 1.194115, 1.440849, 1.505033, 1.322044, 1.550159, 1.51661, 2.150139, 1.810914, 1.559174, 1.675794, 0, 1.391279, 1.861442, 1.454259, 1.699425, 1.214259, 1.087062, 1.372476, 0, 0.992539, 1.281612, 1.05784, 1.319245]` after removing all 0.

The newer commit 351c2ea2fbb09add93980e2942435f31b114047c had geomean speedup of `1.6468495172485` using the following raw data `[1.469446, 1.48596, 2.37428, 1.294068, 1.196943, 1.248378, 1.155319, 1.781833, 1.28924, 3.977822, 3.357135, 0, 1.055654, 1.198194, 1.71543, 0, 2.061835, 1.375784, 1.18559, 3.397077, 1.397325, 1.219341, 3.486337, 2.022329, 1.45552, 1.727281, 2.198778, 1.889907, 1.414192, 1.765933, 2.376041, 1.338445, 1.907912, 1.658857, 0, 1.91456, 1.866376, 1.39469, 0, 3.482202, 1.524609, 1.542552, 1.448312, 0, 0, 0.867727, 0.630242, 2.478057, 1.745571, 11.094336, 1.292214, 3.532874, 1.805928, 1.193, 1.438992, 1.499049, 1.321493, 1.553824, 1.504925, 2.192116, 1.758043, 1.570732, 1.676315, 0, 1.386284, 1.860215, 1.456452, 1.69645, 1.195755, 1.087526, 1.368702, 0, 0.993254, 1.286358, 0.996586, 1.304284]` after removing all 0.

There was indeed an increase from `1.4915172412148x → 1.6468495172485x`.  I notice that `maml` speed up was `0.000805` in the older commit (non-zero and was included) and `0` in the newer one (zero and was excluded).  So I think this value brought the geomean down.

**Comment by huydhn** [comment]
> Another example https://hud.pytorch.org/benchmark/torchbench/inductor_with_cudagraphs?startTime=Tue,%2016%20May%202023%2015:24:09%20GMT&stopTime=Tue,%2023%20May%202023%2015:24:09%20GMT&mode=training&dtype=amp&lBranch=main&lCommit=b91eb97d34536dbdf22bbf7555a8e64ca7932c51&rBranch=main&rCommit=e9a7115605ee5b6ae38ea5716a4abea5aa415333 shows no change in peak memory compression ratio, but the summary says there was a .01 difference.

As for this error, this is due to rounding error in the dashboard.  I'm working on a fix to make sure that all the calculations are done without truncation.

**Comment by ezyang** [comment]
> I notice that maml speed up was 0.000805 in the older commit (non-zero and was included) and 0 in the newer one (zero and was excluded).

Hmm, isn't our methodology that any speedups which are less than 1 are excluded (because ostensibly you'll use eager mode instead, in this case?) cc @jansel

**Comment by jansel** [comment]
> > I notice that maml speed up was 0.000805 in the older commit (non-zero and was included) and 0 in the newer one (zero and was excluded).
> 
> Hmm, isn't our methodology that any speedups which are less than 1 are excluded (because ostensibly you'll use eager mode instead, in this case?) cc @jansel

Yes this is correct.

**Comment by huydhn** [comment]
Ok, this needs to be fixed asap then.  I will push a PR for this first.  It's indeed the case https://github.com/pytorch/pytorch/blob/main/benchmarks/dynamo/runner.py#L760-L764 with `self.get_passing_entries(compiler, df).clip(1)`

**Comment by huydhn** [comment]
https://github.com/pytorch/test-infra/pull/4212 ready for review
