### ISSUE TITLE
Dashboard landing page does not show the default benchmark result

### ISSUE THREAD

**Issue by desertfire** [pytorch/test-infra#4304]
The default Suite is "Torchbench", but now it shows the newly added sub-suite (Dynamic or Blueberries) results instead.

Another default view request, can we set the default Precision of inference to be bfloat16 instead of amp? Thanks.

**Comment by huydhn** [comment]
Good catch.  Let me take a look.  There is probably a missing step somewhere in https://github.com/pytorch/test-infra/pull/4292
