### ISSUE TITLE
Fix logic for disabling tests from hud

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/test-infra#4481]
There are some subtle differences in how the CI expects the naming to be on issues that call out flaky tests.  This results in corner cases where tests don't always get disabled when necessary.

This ask has two parts:
1. Mitigate this by adding instructions to our runbook explaining how to manually identify what the test name should actually be in such corner cases
2. Fix HUD's logic to actually make it more consistent with what the CI expects (or make CI accept HUD's naming format)

**Comment by clee2000** [comment]
I think this got fixed by https://github.com/pytorch/pytorch/pull/104002.  All cases I've seen recently are that the test doesn't call super().setUp() when reimplementing setUp() or some variation of this
