### ISSUE TITLE
[flaky test bot] marking owners as unknown even though they should be known

### ISSUE THREAD

**Issue by janeyx99** [pytorch/test-infra#454]
See: https://github.com/pytorch/pytorch/issues/81212#issuecomment-1182008282 and https://github.com/pytorch/pytorch/issues/81082#issuecomment-1182044727

**Comment by clee2000** [comment]
A few more examples:
https://github.com/pytorch/pytorch/issues/83029
https://github.com/pytorch/pytorch/issues/83027
https://github.com/pytorch/pytorch/issues/83026
https://github.com/pytorch/pytorch/issues/83028
