### ISSUE TITLE
Out of disk space for macOS runner (i-04dc96c56861d7402)

### ISSUE THREAD

**Issue by seemethere** [pytorch/test-infra#4554]
https://github.com/pytorch/pytorch/actions/runs/6089209573/job/16521521089#step:2:94

Creating an issue for visibility here

**Comment by malfet** [comment]
@osalpekar , @ZainRizvi same as another issue filed by ezyang: imo we should close them when fixed (and may be aggregate into a bigger themes) For example, is there an alerting for the oncall?

**Comment by huydhn** [comment]
@DanilBaibak Do you have any update here on preventing this issue from happening?

**Comment by DanilBaibak** [comment]
Yes! We currently setup automated cattle spa workflow for macOS runners. TLDR - we automatically terminate old instances and spin up new ones daily. The current state of disk space for macOS runner looks much better:
![Uploading Screenshot 2023-11-02 at 11.01.14.png…]()
