### ISSUE TITLE
Dr CI is not updating

### ISSUE THREAD

**Issue by clee2000** [pytorch/test-infra#4598]
I've seen a number of dr ci comments that say pending, but when you look at the hud link, there are failing jobs.  The Dr CI comment hasn't been updated in a while.

Possible causes:
* hitting rate limits causing updates to not complete
* gha unable to schedule every 15 minutes accurately
* wrong sql queries + other code bugs

**Comment by huydhn** [comment]
Do you think this is related to my recent change https://github.com/pytorch/test-infra/pull/4589 to wait for JSON response from Dr.CI API call?  Although I kind of remember seeing stale Dr.CI comment before.

Spot checking at a schedule run https://github.com/pytorch/test-infra/actions/runs/6342420083/job/17228123956 looks ok, although it doesn't seem to include all open PR in the response?

**Comment by clee2000** [comment]
It's only supposed to update prs that had workflows finish recently

**Comment by malfet** [comment]
Thank you for filing the issue, I was about to mention https://github.com/pytorch/pytorch/pull/110221 as an example, where all workflows have finished 4+ hours ago, but DrCI still claims 5 jobs are pending..)
