### ISSUE TITLE
[BE] [HUD] Have the job failures in the "more like this" page point to the hud page for the relevant commit

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/test-infra#4600]
This will make it easier to pinpoint the root cause of a new class of issues by seeing which PR was ground zero.

Example link: https://hud.pytorch.org/failure/'DummyXPUModule'%20has%20no%20attribute%20 

So the list of jobs with similar failures would get a new link pointing to the commit's hud page

Going from something like this:
![Image](https://github.com/pytorch/test-infra/assets/4468967/a9377d1d-6260-4f55-af22-83ebb94cd3aa)

To this 
![Image](https://github.com/pytorch/test-infra/assets/4468967/6efce293-bf03-419e-9a5c-a44cca14ab01)

**Comment by clee2000** [comment]
Not entire the same, but there is now a link to the commit after https://github.com/pytorch/test-infra/pull/4739
