### ISSUE TITLE
OS X runners out of disk space

### ISSUE THREAD

**Issue by ezyang** [pytorch/test-infra#4635]
https://github.com/pytorch/pytorch/actions/runs/6511474800/job/17687246136

**Comment by malfet** [comment]
I assume we've cleaned those one up already, but @ZainRizvi, @osalpekar  just curious, had this issue appeared in any of the team triages so far? Should somebody should take the responsibility of initial triage of all test infra issues?

**Comment by huydhn** [comment]
Resolving this in favor of https://github.com/pytorch/test-infra/issues/4554
