### ISSUE TITLE
Mergebot should reopen a PR when it's reverted

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/test-infra#4692]
**Goal**
When mergebot reverts a PR, reopen that PR as well.  This'll make tracking reverted PRs easier for the authors

**Caveat**
It appears that sometimes github can't reopen regular PRs.  It's been reported this can happen when the branch has been deleted or if it's been "merged" (potentially meaning this feature could only work for ghstack PRs), but this needs more  investigation

**Comment by malfet** [comment]
`gh_fetch_url("https://api.github.com/repos/malfet/deleteme/pulls/57", method="PATCH", data={"state":"open"})` is all it takes

**Comment by malfet** [comment]
@huydhn branches are not auto-deleted, and only owner can restore a branch, so if PR is reverted, we should just try to revert as a firs step

**Comment by malfet** [comment]
And it works: https://github.com/malfet/deleteme/pull/58 Cherry-picking PRs into torch
