### ISSUE TITLE
Pytorch-bot cancels merge job

### ISSUE THREAD

**Issue by malfet** [pytorch/test-infra#4733]
According to annotations in  https://github.com/pytorch/pytorch/actions/runs/6869460590
Merge was cancelled by pytorch-bot:
<img width="478" alt="image" src="https://github.com/pytorch/test-infra/assets/2453524/d9140020-5113-4f67-94de-d163871cab3b">

Would be good to have some idea why it happened

**Comment by clee2000** [comment]
Should be fixed by https://github.com/pytorch/test-infra/pull/4732

**Comment by ZainRizvi** [comment]
Eli: Would be nice to add a clickable link to the PR

**Comment by clee2000** [comment]
fix got merged, and the clickable link got added in https://github.com/pytorch/pytorch/pull/113712, closing
