### ISSUE TITLE
Allow pytorchbot to add labels on issues

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#4738]
This is a feature request from ET team where they want to grant some external devs permission to add labels to issues, i.e. "partner: xyz" for triaging.  People can use `@pytorchbot label`, but this only works for PR atm.  I try `@pytorchbot label` on an issue and it doesn't work, i.e. https://github.com/pytorch/pytorch/issues/113419#issuecomment-1813183399

Another approach would be to grant write permission to a group of contributors, i.e. from Apple.  This is the same approach PyTorch is using atm.  But ET team doesn’t know yet who exactly will be working on the backend, grant permission to certain POCs may not scale.

Another feature is to have `@pytorchbot close -m MESSAGE` on an issue to close the issue.  We don't have this feature on the bot, so I'm adding it here for further discussion.

cc @guangy10 @ZainRizvi @clee2000 @kit1980 @PaliC

**Comment by huydhn** [comment]
AI: Take a look at auto label bot to see if it could help here

**Comment by guangy10** [comment]
Any feedback/update on this feature request. I'd love to have it and once it's available we can update the ET documentation to guide contributors using it. It will help ET partners (anyone from their side) for issue triaging w/o bothering us to grant permissions explicitly. It is a pain to figure out and manage who should have the triaging/write permissions.

**Comment by huydhn** [comment]
> Any feedback/update on this feature request. I'd love to have it and once it's available we can update the ET documentation to guide contributors using it. It will help ET partners (anyone from their side) for issue triaging w/o bothering us to grant permissions explicitly. It is a pain to figure out and manage who should have the triaging/write permissions.

Just FYI, we have added this into the current sprint, @PaliC will help take a look at the issue

**Comment by PaliC** [comment]
Added these features through this stack https://github.com/pytorch/test-infra/pull/4781

For closing prs/issues I feel like a message is uneeded as its a reversible low consequence action folks can do anyways.

**Comment by guangy10** [comment]
> Added these features through this stack #4781
> 
> For closing prs/issues I feel like a message is uneeded as its a reversible low consequence action folks can do anyways.

I think closing an issue with a short message would be more helpful to understand the status change, e.g. close because the work is done, or not longer valid, or covered by another feature, etc. It's okay to make it not mandatory imo. @PaliC users can specify the message optionally right?

**Comment by PaliC** [comment]
@guangy10 Very much so, its not like the message gets propagated anywhere haha.

**Comment by PaliC** [comment]
@guangy10 Once you write @pytorchbot close, you should be able to just write a message on the next line as you would with @pytorchbot merge or @pytorchbot revert

It's not useful to add an argument for a message if we're not using it anywhere.
