### ISSUE TITLE
AWS OIDC integration with Vercel

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#4789]
Per the shoutout from @jeanschmidt, we are moving away from using fixed AWS credentials to [OIDC](https://docs.google.com/document/d/1IMAGE9RMIcZBcTaEeTOivySJZpE74bq5IJAwzdlxxfw).  As part of this, we need to figure out how Vercel integrates with OIDC here to decide what to do next.  PyTorch bot and various HUD API are at risk of losing access otherwise.

cc @jeanschmidt @malfet @seemethere

**Comment by huydhn** [comment]
The key used by Vercel can be found at https://vercel.com/fbopensource/torchci/settings/environment-variables

**Comment by huydhn** [comment]
This could become a blocker (I really hope not).  My doc search so far on Vercel seems to point to their practice of using fixed AWS credentials:

* https://vercel.com/templates/next.js/aws-dynamodb-with-nextjs-api-routes
* https://vercel.com/guides/how-can-i-use-aws-s3-with-vercel
* https://vercel.com/guides/how-can-i-use-aws-sdk-environment-variables-on-vercel

**Comment by malfet** [comment]
Alternatively we can install npm package that implements OpenAI as part of lambda and store some sort of token to ask for those short lived tokens

**Comment by huydhn** [comment]
For the last use case of writing to DynamoDB, I have the experiment PR at https://github.com/pytorch/test-infra/pull/4896#issuecomment-1901689708 and have created a case to Vercel https://vercel.com/fbopensource/~/support/cases/00190921 to see if it can be unblocked.

On the other hand, @jeanschmidt mentions that keeping PyTorch HUD account might be acceptable because it doesn't prose as a CI risk.  If that's the case, we could just narrow the permission on the account to only cover torchci DynamoDB table and be done with it.

**Comment by huydhn** [comment]
https://github.com/pytorch/test-infra/pull/4896#issuecomment-1905212274
