### ISSUE TITLE
[mergebot] Force revert for overriding the internal changes check

### ISSUE THREAD

**Issue by clee2000** [pytorch/test-infra#4797]
I know we've talked about this before but I don't know if we had an issue for it already.  This was brought up again in diff train oncall due to some exceptional circumstances.

The desire is mainly to get around the check for internal changes for when the check is wrong.  This flag shouldn't typically used.  The alternative (used today) is to make a new PR for the revert.

**Comment by malfet** [comment]
Few examples: 
- https://github.com/pytorch/pytorch/pull/115099
- https://github.com/pytorch/pytorch/pull/113115
