### ISSUE TITLE
Create pytorch cherry-pick bot to support release cherry picking

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#4801]
@seemethere has been taking a look at this in https://github.com/pytorch/test-infra/pull/4758

**Comment by huydhn** [comment]
@seemethere Are there any updates on this one?  I could pick this up and get it ready for the next release

**Comment by seemethere** [comment]
> @seemethere Are there any updates on this one? I could pick this up and get it ready for the next release

No updates on my side, don't think I'll have the bandwidth to carry this unfortunately :(

**Comment by huydhn** [comment]
Np, I could reassign it to myself to get this ready before the next release :)

**Comment by huydhn** [comment]
The bot has been in used for a while, so I'm closing this issue now.  Future enhancement will be covered by another ticket.
