### ISSUE TITLE
[codev] Improve the mergeability check for ghexport

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#4816]
When using ghexport to export a stack of diff to OSS, the current mergeability check in `github-export-checks` simply doesn't work.  The current implementation uses https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request to check for the `mergeable` state of a PR.  While this works for a regular PR trying to merge into `main`, it doesn't work for ghstack PRs (even with a depth of 1) because the head will always be mergeable into the base of the stack.

This gap and the fact that fbcode is always older than GitHub due to diff train delay leads to frequent merge conflicts that we have seen from time to time.

We should investigate if there is a better way to perform mergeability check for exported ghstack PRs.

cc @PaliC @clee2000 @kit1980 @malfet

**Comment by PaliC** [comment]
At this point this issue should mostly be solved as we have a job running on ghstack prs now to check mergability. The caveat to this is this job doesn't fail which can mean the user can miss it.

One solution to this is this pr: https://github.com/pytorch/test-infra/pull/4825
Though other suggestions are welcome.

**Comment by PaliC** [comment]
As the following prs are merged, this should be closed now :) 
https://github.com/pytorch/pytorch/pull/115944
https://github.com/pytorch/test-infra/pull/4823
https://github.com/pytorch/test-infra/pull/4825

**Comment by PaliC** [comment]
Note that the inability to merge is no longer covered in github-export-checks as it currently skips OSS CI.
However, making it the job created in https://github.com/pytorch/pytorch/pull/115944 mandatory for force merges similar to linting should cover us here
