### ISSUE TITLE
Auto revert all dependent PRs above a reverted PR in the stack

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#4845]
When reverting a PR in ghstack atm, we usually need to manually revert all dependent PRs on top of it.  We should improve the bot to automatically detect landed dependent PRs on the stack and revert them too (ideally in the reverse order that they were landed).

This is part of the [oncall runbook](https://docs.google.com/document/d/1JBWlm9Aa1jBpaRW3xvHgyTBlmT_8lxH5BpCtJNOjajE), but it's always better QoL to have more automation here. 

https://github.com/pytorch/pytorch/pull/115188 was an example where it was reverted but not the one above it https://github.com/pytorch/pytorch/pull/115210.  And it caused lots of trunk failures (SEV: https://github.com/pytorch/pytorch/issues/116273)

cc @malfet @jeanschmidt @kit1980 @clee2000 @PaliC @seemethere

**Comment by malfet** [comment]
I don't think it needs much discussion to be frank: Phabricator works the same way, merge works the same way, revert should follow the path
