### ISSUE TITLE
Add support for MacOS 14 (Sonoma) runner, or XCode SDK 15?

### ISSUE THREAD

**Issue by beveradb** [pytorch/test-infra#4899]
Hi folks,

Apologies if this is the wrong place to ask, but could we add a macOS 14 runner?

I'm trying to add support for FFT operations which were added to MPS in Sonoma:
https://github.com/pytorch/pytorch/pull/116630

but the CI build fails as it's using the older XCode SDK `MacOSX13.sdk` which doesn't have the header:
```
/Users/ec2-user/runner/_work/pytorch/pytorch/aten/src/ATen/native/mps/MPSGraphSonomaOps.h:3:10: note: did not find header 'MPSGraphFourierTransformOps.h' in framework 'MetalPerformanceShadersGraph' (loaded from '/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks')
```

It seems like there will be a macOS 14 runner image available very soon:
https://github.com/actions/runner-images/pull/9179

and folks in this thread seem to have worked around it by installing a newer XCode SDK on the macOS 13 runner:
https://github.com/actions/runner-images/issues/7508#issuecomment-1892035921

I'd love to hear others' thoughts on how best to resolve this!

Thanks :bow:

**Comment by malfet** [comment]
Installing new SDK is easy, but one should not build PyTorch only for MacOS, but rather build with older SDK, and embed necessary headers, see how it's done for say complex operations, so that one can run the same binary on MacOS 13 and MacOS 14 and use ops when available
