### ISSUE TITLE
ciflow doesn't work if you are a third party contributor

### ISSUE THREAD

**Issue by seemethere** [pytorch/test-infra#4915]
Found this interesting interaction with ciflow after https://github.com/pytorch/test-infra/pull/4892.

Basically ciflow doesn't work on third party PRs even if the person applying the label is a first party contributor.

Probably the intended behavior but just wanted to document here.

https://github.com/pytorch/pytorch/pull/117039#issuecomment-1918111287

**Comment by malfet** [comment]
I think the problem is that there are no pull.yml in the signal, but according to GraphQL those require workflow approval, let's see if this is doable via CLI

**Comment by malfet** [comment]
This looks like a github hiccup/expected behavior as no pull request events were scheduled for the latest commit on the PR:
```
% gh api "/repos/pytorch/pytorch/actions/runs?head_sha=c04cc5d816ca6ebb3293cd8aa223ccc0d343ce07&event=pull_request"
{
  "total_count": 0,
  "workflow_runs": []
}
```

**Comment by malfet** [comment]
But looks like this is by design: for action to run on `pull_request` event,  one must be create `merge` branch, is is not possible as merge conflicts exits, see long (and sometimes unprofessional) discussion here: https://github.com/orgs/community/discussions/26304

**Comment by seemethere** [comment]
Okay makes sense to me, closing this!
