### ISSUE TITLE
Giving approvals for forked pull requests is really annoying

### ISSUE THREAD

**Issue by clee2000** [pytorch/test-infra#4938]
Having to click approve for merge, and then approve again for trunk is really annoying.  It's unclear how many clicks are needed + how long one needs to wait for the workflows to trigger

If possible, the next time this happens, please ping @clee2000 or @huydhn so we can use it as a test or go through the flow ourselves 

Ok to click every time a PR is updated, but would like to just click once for all the workflows on that pull request

Solution 1: There exists a git api https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#approve-a-workflow-run-for-a-fork-pull-request:
* if other runs have been approved, then approve all runs (like ciflow tags)

Solution 2: Stop running bc lint on labeled/unlabeled, move to mechanism like pr sanity checks

Approvals can be turned off when we have ephemeral runners (ARC) at end of half

Workflows:
* probably trunk
* bc lint on merging label

cc @albanD

**Comment by clee2000** [comment]
short term fix is also to stop running bc lint on labeled/unlabeled

**Comment by huydhn** [comment]
For the second option, I think we could replace the labeled/unlabeled triggers with an API call to get the list of labels from the PR dynamically.  Then adding the suppressing label then rerunning bc linter will work.  A small drawback is that the contributors won't have the permission to rerun workflow by themselves, but it looks better than pushing a new commit just to pass bc linter.  The same step could also be done for pr sanity check, which requires pushing a commit to suppress atm.

cc @izaitsevfb

**Comment by huydhn** [comment]
Let me bump this to high priority, like looking into https://github.com/pytorch/pytorch/pull/120040/checks and I see bc lint running and cancelling many times.

**Comment by huydhn** [comment]
AI: During the discussion today, I'll implement the fix on Dr.CI so that it takes into account the bc linter suppression label on the PR and make bc linter job as an expected failure and doesn't block merge if it fails with that label on.  Then we can remove the label/unlabel triggers on the workflow.

**Comment by huydhn** [comment]
PR is ready for reviewed at https://github.com/pytorch/test-infra/pull/4956

**Comment by huydhn** [comment]
This should be fixed now and we only need one approval every time the PR is created or updated.
