### ISSUE TITLE
Labeler and pytorch bot are stepping on each other foot when it comes to attach ciflow labels

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#4950]
Related to https://github.com/pytorch/test-infra/issues/4938.

Some folks are pointing out the peculiar behavior when `ciflow` label is added to the PR only to be rejected by the bot, i.e. https://github.com/pytorch/pytorch/pull/115539#issuecomment-1900174263.

Atm, we are 3 ways to attach a labels to PR:

1. via the labeler rule https://github.com/pytorch/pytorch/blob/main/.github/labeler.yml#L11
2. via the bot, i.e. `@pytorchbot label ciflow/trunk`
3. manually done by the reviewer (or whoever has write access to the repo)

The current implementation catches all of them correctly.  Nevertheless, a better UX would be to not attach the `ciflow` label there in the first place if the PR comes from an outside collaborator.

**Comment by huydhn** [comment]
Could be resolved after https://github.com/pytorch/test-infra/pull/4995 lands and labeler workflow cleaned up

**Comment by clee2000** [comment]
https://github.com/pytorch/test-infra/pull/5025 and https://github.com/pytorch/test-infra/pull/5023 should also help with this

**Comment by clee2000** [comment]
I haven't seen any bot fighting in the past two days after these PRs were merged.  
If someone does find cases, please re open and include a link
