### ISSUE TITLE
[drci] Workflow file errors remain after they are retried

### ISSUE THREAD

**Issue by clee2000** [pytorch/test-infra#4969]
Dr CI does not handle workflow file errors very well after they are retried

### :test_tube: See artifacts and rendered test results at [hud.pytorch.org/pr/120358](https://hud.pytorch.org/pr/120358)
* :page_facing_up: Preview [Python docs built from this PR](https://docs-preview.pytorch.org/pytorch/pytorch/120358/index.html)
* :page_facing_up: Preview [C++ docs built from this PR](https://docs-preview.pytorch.org/pytorch/pytorch/120358/cppdocs/index.html)
* :question: Need help or want to give feedback on the CI? Visit the [bot commands wiki](https://github.com/pytorch/pytorch/wiki/Bot-commands) or our [office hours](https://github.com/pytorch/pytorch/wiki/Dev-Infra-Office-Hours)

Note: Links to docs will display an error until the docs builds have been completed.
## :heavy_exclamation_mark: 1 Merge Blocking SEVs
There is 1 active merge blocking SEVs.  Please view them below:
* (merge blocking) [CI is too red, viable/strict branch didn't update for 5 days](https://hud.pytorch.org/pytorch/pytorch/issues/120368)

If you must merge, use `@pytorchbot merge -f`.

## :white_check_mark: You can merge normally! (5 Unrelated Failures)
As of commit c83eb30280626ff84d7a2950d200cb3257e16fb2 with merge base 8fa634070189a5567b7bb0ddf1f389d6e43bebe5 (<sub><sub><img alt="image" width=70 src="https://img.shields.io/date/1708556967?label=&color=FFFFFF&style=flat-square"></sub></sub>):
<details ><summary><b>FLAKY</b> - The following jobs failed but were likely due to flakiness present on trunk:</summary><p>

* [.github/workflows/generated-linux-binary-libtorch-cxx11-abi-main.yml](https://hud.pytorch.org/pr/pytorch/pytorch/120358#7997133699) ([gh](https://github.com/pytorch/pytorch/actions/runs/7997133699))
* [.github/workflows/generated-linux-binary-libtorch-pre-cxx11-main.yml](https://hud.pytorch.org/pr/pytorch/pytorch/120358#7997133689) ([gh](https://github.com/pytorch/pytorch/actions/runs/7997133689))
* [.github/workflows/generated-linux-binary-manywheel-main.yml](https://hud.pytorch.org/pr/pytorch/pytorch/120358#7997133687) ([gh](https://github.com/pytorch/pytorch/actions/runs/7997133687))
* [.github/workflows/trunk.yml](https://hud.pytorch.org/pr/pytorch/pytorch/120358#7997133683) ([gh](https://github.com/pytorch/pytorch/actions/runs/7997133683))
* [trunk / win-vs2019-cpu-py3 / test (default, 1, 3, windows.4xlarge.nonephemeral)](https://hud.pytorch.org/pr/pytorch/pytorch/120358#21843090580) ([gh](https://github.com/pytorch/pytorch/actions/runs/7997633258/job/21843090580))
    `test_nn.py::TestNNDeviceTypeCPU::test_clip_grad_norm_foreach_False_norm_type_0_5_cpu`
</p></details>

This comment was automatically generated by Dr. CI and updates every 15 minutes.

**Comment by huydhn** [comment]
I think this is the same issue as https://github.com/pytorch/test-infra/issues/4987 and is fixed by https://github.com/pytorch/test-infra/pull/4998

**Comment by huydhn** [comment]
AI: We need to handle the case where the failing workflow keep showing up on Dr.CI box even after they have been retried.  Otherwise, people will need to force merge to land their changes

**Comment by clee2000** [comment]
I think this is fixed by https://github.com/pytorch/test-infra/pull/5038

Leaving this open because the second AI item mentioned by Huy in the previous comment is not covered by this and I'm not sure if we still want to do it

**Comment by huydhn** [comment]
This issue has been fixed.  There are some cases like https://github.com/pytorch/pytorch/pull/123104 where the workflow path still appears in the job name used by mergebot, but it looks like a different issues https://github.com/pytorch/pytorch/issues/122422
