### ISSUE TITLE
Test github GPU runner on test-infra linux-job

### ISSUE THREAD

**Issue by atalman** [pytorch/test-infra#4970]
Test and see if generic linux_job: 
https://github.com/pytorch/test-infra/blob/main/.github/workflows/linux_job.yml

Works with Linux GPU github runners

Current infra offerings: https://www.internalfb.com/intern/opensource/ci/github-actions/runners

**Comment by osalpekar** [comment]
I think we can first test with `ubuntu-latest`. We can also try one of the workflows in torchtune with the A10G instances available in pytorch-labs that @seemethere mentioned.

**Comment by atalman** [comment]
PR to test the workflows: https://github.com/pytorch/test-infra/pull/4975
