### ISSUE TITLE
[Dr CI] Classifications inaccurate

### ISSUE THREAD

**Issue by clee2000** [pytorch/test-infra#5028]
Ed reports that all failures are caused by the PR https://github.com/pytorch/pytorch/pull/122273 but are incorrectly classified as flaky

<details>
<summary> Dr CI comment: </summary>

### :test_tube: See artifacts and rendered test results at [hud.pytorch.org/pr/122273](https://hud.pytorch.org/pr/122273)
* :page_facing_up: Preview [Python docs built from this PR](https://docs-preview.pytorch.org/pytorch/pytorch/122273/index.html)
* :page_facing_up: Preview [C++ docs built from this PR](https://docs-preview.pytorch.org/pytorch/pytorch/122273/cppdocs/index.html)
* :question: Need help or want to give feedback on the CI? Visit the [bot commands wiki](https://github.com/pytorch/pytorch/wiki/Bot-commands) or our [office hours](https://github.com/pytorch/pytorch/wiki/Dev-Infra-Office-Hours)

Note: Links to docs will display an error until the docs builds have been completed.

## :white_check_mark: You can merge normally! (12 Unrelated Failures)
As of commit 19314f56e1424a1d6ae82ed624f093c4a96301a7 with merge base failed to retrieve merge base, please contact dev infra (<sub><sub><img alt="image" width=70 src="https://img.shields.io/date/946684800?label=&color=FFFFFF&style=flat-square"></sub></sub>):
<details ><summary><b>FLAKY</b> - The following jobs failed but were likely due to flakiness present on trunk:</summary><p>

* [inductor / cuda12.1-py3.10-gcc9-sm86 / test (dynamic_inductor_torchbench, 2, 2, linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/122273#22866232124) ([gh](https://github.com/pytorch/pytorch/actions/runs/8353553791/job/22866232124))
    `moco`
* [inductor / cuda12.1-py3.10-gcc9-sm86 / test (inductor_distributed, 1, 1, linux.g5.12xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/122273#22866231062) ([gh](https://github.com/pytorch/pytorch/actions/runs/8353553791/job/22866231062))
    `distributed/test_dynamo_distributed.py::TestFakeDistributedSingleProc::test_hf_bert_ddp_aot_eager`
* [inductor / cuda12.1-py3.10-gcc9-sm86 / test (inductor_torchbench, 2, 2, linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/122273#22866231585) ([gh](https://github.com/pytorch/pytorch/actions/runs/8353553791/job/22866231585))
    `moco`
* [inductor / cuda12.1-py3.10-gcc9-sm86 / test (inductor, 1, 1, linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/122273#22866230947) ([gh](https://github.com/pytorch/pytorch/actions/runs/8353553791/job/22866230947))
    `distributed/test_dynamo_distributed.py::TestFakeDistributedSingleProc::test_hf_bert_ddp_aot_eager`
* [inductor / rocm6.0-py3.8-inductor / test (inductor, 1, 1, linux.rocm.gpu.2)](https://hud.pytorch.org/pr/pytorch/pytorch/122273#22867013227) ([gh](https://github.com/pytorch/pytorch/actions/runs/8353553791/job/22867013227))
    `distributed/test_dynamo_distributed.py::TestFakeDistributedSingleProc::test_symbol_splitting`
* [inductor-periodic / cuda12.1-py3.10-gcc9-sm86-periodic-dynamo-benchmarks / test (aot_eager_torchbench, 2, 2, linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/122273#22866211029) ([gh](https://github.com/pytorch/pytorch/actions/runs/8353553788/job/22866211029))
    `moco`
* [inductor-periodic / cuda12.1-py3.10-gcc9-sm86-periodic-dynamo-benchmarks / test (dynamic_aot_eager_torchbench, 2, 2, linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/122273#22866211580) ([gh](https://github.com/pytorch/pytorch/actions/runs/8353553788/job/22866211580))
    `moco`
* [inductor-periodic / cuda12.1-py3.10-gcc9-sm86-periodic-dynamo-benchmarks / test (dynamo_eager_torchbench, 2, 2, linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/122273#22866210396) ([gh](https://github.com/pytorch/pytorch/actions/runs/8353553788/job/22866210396))
    `moco`
* [pull / linux-focal-cuda11.8-py3.10-gcc9 / test (distributed, 2, 3, linux.8xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/122273#22865921586) ([gh](https://github.com/pytorch/pytorch/actions/runs/8353552343/job/22865921586))
    `distributed/test_dynamo_distributed.py::TestFakeDistributedSingleProc::test_symbol_splitting`
* [pull / linux-focal-cuda12.1-py3.10-gcc9-sm86 / test (default, 3, 5, linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/122273#22866209746) ([gh](https://github.com/pytorch/pytorch/actions/runs/8353552343/job/22866209746))
    `dynamo/test_logging.py::LoggingTests::test_ddp_graphs`
* [pull / linux-focal-cuda12.1-py3.10-gcc9-sm86 / test (default, 5, 5, linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/122273#22866210045) ([gh](https://github.com/pytorch/pytorch/actions/runs/8353552343/job/22866210045))
    `inductor/test_layout_optim.py::TestLayoutOptim::test_2conv_with_graph_break`
* [pull / linux-jammy-py3.8-gcc11 / test (distributed, 1, 2, linux.2xlarge)](https://hud.pytorch.org/pr/pytorch/pytorch/122273#22865715793) ([gh](https://github.com/pytorch/pytorch/actions/runs/8353552343/job/22865715793))
    `distributed/test_dynamo_distributed.py::TestFakeDistributedSingleProc::test_symbol_splitting`
</p></details>

This comment was automatically generated by Dr. CI and updates every 15 minutes.

</details>

cc @huydhn

**Comment by malfet** [comment]
Is there a good documentation where current classification logic explained? And perhaps first step is to add some sort of a feedback button, that one can click if they believe that classification is incorrect?

**Comment by huydhn** [comment]
AI: Write up a wiki on how Dr. CI categorization works, how to report issue, and how to debug them

**Comment by huydhn** [comment]
As the first step, the fix is here https://github.com/pytorch/test-infra/pull/5034, this is a regression because the merge base date has now been set to 0 instead of an empty string, which widens the similar failure search to include everything since "the beginning of time".  It's very likely then to find similar failures then and it causes FP in Dr. CI flaky classification.

Note that this issues only happens with ghstack PRs where merge base date is not available.
