### ISSUE TITLE
Auto-approve workflow runs for "safe" forked pull requests

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/test-infra#5097]
# Ask
When a first time contributor submits a PR that does not modify any of the directories used for workflow execution, auto-approve its workflow runs 

Api: https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#approve-a-workflow-run-for-a-fork-pull-request

# Context
Today pytorch devs have to manually hit the "approve" button when on PRs from first time contributors. This slows down the review process and adds extra iterations since it takes over 3 hours for the CI jobs to run and validate the changes. This is a frequent complaint from pytorch devs

**Comment by clee2000** [comment]
cc @malfet @kit1980 Is this safe?

**Comment by malfet** [comment]
I don't think there is a way to identify a subset of "safe" files as modifying any  file that gets executed in course of CI allows one to setup a reverse remote shell into the runner

**Comment by kit1980** [comment]
To give one concrete example, any existing test can be modified to run something else than just a test.

**Comment by kit1980** [comment]
Also currently require we approvals for every change for all forked PRs, not only for first time contributors.
