### ISSUE TITLE
[Dr CI] Wrong classification for XLA

### ISSUE THREAD

**Issue by clee2000** [pytorch/test-infra#5139]
Pretty sure the xla failure on this was real

### :test_tube: See artifacts and rendered test results at [hud.pytorch.org/pr/124920](https://hud.pytorch.org/pr/124920)
* :page_facing_up: Preview [Python docs built from this PR](https://docs-preview.pytorch.org/pytorch/pytorch/124920/index.html)
* :page_facing_up: Preview [C++ docs built from this PR](https://docs-preview.pytorch.org/pytorch/pytorch/124920/cppdocs/index.html)
* :question: Need help or want to give feedback on the CI? Visit the [bot commands wiki](https://github.com/pytorch/pytorch/wiki/Bot-commands) or our [office hours](https://github.com/pytorch/pytorch/wiki/Dev-Infra-Office-Hours)

Note: Links to docs will display an error until the docs builds have been completed.

## :white_check_mark: You can merge normally! (2 Unrelated Failures)
As of commit a6516ea6789e12a1a80a8c8cc7ce63698d443821 with merge base 59a1f1f308545e3ac1d81940a51f8dc0db3d82d4 (<sub><sub><img alt="image" width=70 src="https://img.shields.io/date/1714026931?label=&color=FFFFFF&style=flat-square"></sub></sub>):
<details ><summary><b>FLAKY</b> - The following job failed but was likely due to flakiness present on trunk:</summary><p>

* [pull / linux-focal-py3_8-clang9-xla / test (xla, 1, 1, linux.12xlarge)](https://hud.pytorch.org/pr/pytorch/pytorch/124920#24271828087) ([gh](https://github.com/pytorch/pytorch/actions/runs/8829224984/job/24271828087))
    `test_all_cpu_tensor`
</p></details>
<details ><summary><b>BROKEN TRUNK</b> - The following job failed but was present on the merge base:</summary><p>👉 <b>Rebase onto the `viable/strict` branch to avoid these failures</b></p><p>

* [pull / linux-focal-cuda12.1-py3.10-gcc9-sm86 / test (default, 5, 5, linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/124920#24269813617) ([gh](https://github.com/pytorch/pytorch/actions/runs/8829224984/job/24269813617))
    `inductor/test_cudagraph_trees.py::CudaGraphTreeTests::test_mutation_cudagraph_managed_tensors_config_backend_cudagraphs`
</p></details>

This comment was automatically generated by Dr. CI and updates every 15 minutes.

**Comment by clee2000** [comment]
I think it matched against things like https://github.com/pytorch/pytorch/actions/runs/8819380894/job/24214658473 which has a different error trace but the same test name

**Comment by huydhn** [comment]
I'm trying to figure out a solution for this case.  From what I see, XLA error matching is sometime not good because I have not been paying to much attention on what is running on XLA size to have good log classifier support.  One common mismatch is `ModuleNotFoundError: No module named 'torch.version'` which appears on all XLA test job.

**Comment by huydhn** [comment]
This has been fixed by https://github.com/pytorch/test-infra/pull/5151, so I will close this.
