### ISSUE TITLE
Request for A100 CI runners with 80GB of memory

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#5176]
All our existing A100 runners have 40GB memory.  @yanboliang report that this might be not enough to run all benchmark experiments with llama 7B.  Specifically, one experiment https://github.com/pytorch/pytorch/blob/main/benchmarks/gpt_fast/benchmark.py#L40-L46 requires 7 * 8 = 56GB of memory and
the workaround in https://github.com/pytorch/pytorch/pull/125608 is needed to reduce the number of layers to fit into 40GB memory limit.  Internally, we have A100 with 80GB of memory for similar experiements.

GCP provides A100 80GB https://cloud.google.com/compute/docs/gpus.  I don't have the context on why we use the smaller 40GB variant instead.  So, I'm creating this issue to see if we could replace all or a subset of our A100 40GB CI runners with 80GB runners instead.

cc @seemethere @DanilBaibak @jeanschmidt @malfet @ZainRizvi @yanboliang

**Comment by huydhn** [comment]
The A100 runners from TorchBench also have 40GB https://github.com/pytorch/benchmark/actions/runs/8973626817/job/24644237465#step:3:28

**Comment by yanboliang** [comment]
Yea, we are working on benchmarking torch.compile performance on series of LLM models (Llama2, Llama3, Mixtral, DBRX, Grok, Mamba, etc) against the SOTA numbers with the most common used hardware (A100 + H100). The A100 + 40GB is not the most common used in the industry, it would be great to use A100 + 80GB if we have resources. cc @Chillee

**Comment by huydhn** [comment]
Per the chat with @seemethere and @kit1980, I think we need to look at ServiceLab to get the capacity we need. OSS A100 GCP fleet is not expected to grow further.  This is a new area, so I'll keep you posted with the findings in the upcoming weeks.

**Comment by ZainRizvi** [comment]
Conclusion: We won't be able to get these machines in the near future. We'll be exploring potential alternatives
