### ISSUE TITLE
Request for cooler tab names on hud

### ISSUE THREAD

**Issue by angelayi** [pytorch/test-infra#5185]
This is a super minor request, but for hud pages that show a specific PR's CI run, it would be cool we could rename the tab name to contain the PR title or the PR number, just so we could tell the difference between tabs.

For example, right now I see something like:
<img width="386" alt="image" src="https://github.com/pytorch/test-infra/assets/10901756/2987cdca-717b-4ac8-a9da-9a214608c81c">

But it would be clearer if I could see something like:
<img width="385" alt="image" src="https://github.com/pytorch/test-infra/assets/10901756/5ea591b7-ffb9-410e-8d1b-508691e0b8a2">

Anyways, this is just a minor request -- maybe I'll look into it when I have time or unless Cat doesn't want to do it :> 

cc @clee2000

**Comment by malfet** [comment]
Work in progress PR (need to figure out how to align Pages and Router together)

**Comment by huydhn** [comment]
This one is done as part of the hackaday last month
