### ISSUE TITLE
Create a HUD snapshot link that can be bookmarked and shared

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#5228]
This is similar to the take snapshot button on inductor dashboard https://hud.pytorch.org/benchmark/compilers

![Screenshot 2024-05-20 at 18 28 49](https://github.com/pytorch/test-infra/assets/475357/5b0ce094-7461-4406-98e7-ba3777f8084a)

Once click, the link to the current HUD view is copied to clipboard and can be shared.  Following the link will show the exact same view.  This is useful to capture a HUD at a specific moment, i.e. to document a sev.

**Comment by malfet** [comment]
Done
