### ISSUE TITLE
Improve UX for "Queue times historical" graph on HUD metrics

### ISSUE THREAD

**Issue by jithunnair-amd** [pytorch/test-infra#5260]
Is there a way to improve the UX on https://hud.pytorch.org/metrics for the "Queue times historical" graph? We often want to have just the ROCm labels showing, but the way to disable all the others is quite clunky.

In general, a Select/Unselect All feature would be very helpful.

**Comment by clee2000** [comment]
Fixed by https://github.com/pytorch/test-infra/pull/5290
