### ISSUE TITLE
HUD refresh causes you to lose position

### ISSUE THREAD

**Issue by ezyang** [pytorch/test-infra#5279]
A common workflow is as errors come into HUD, you start working on fixing them. That means scrolling down to one of the log windows, opening it, and keeping it open. However, when autorefresh happens, we lose our scroll position and go back to the top of the page. Please don't do that. The easiest fix is to add a toggle for disabling autorefresh.

**Comment by jithunnair-amd** [comment]
A similar issue also exists on metrics.pytorch.org HUD when one is interacting with any of the charts and has filters set up. It's annoying.

**Comment by clee2000** [comment]
I've fixed one issue contributing to this in https://github.com/pytorch/test-infra/pull/5504 @ezyang @andrewor14 please let me know if its still happening (also if its reproducible and you could include a screen recording thatd be helpful)
