### ISSUE TITLE
Confusing Build Official Docker Images / validate job names on nightly HUD

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#5345]
I’m seeing the Docker image nightly tag as part of the job name https://hud.pytorch.org/hud/pytorch/pytorch/nightly/1?per_page=50&name_filter=Build%20Official%20Docker%20Images because it’s part of the configuration matrix there I guess.  The side-effect is that there is a new column for that everyday on HUD https://hud.pytorch.org/hud/pytorch/pytorch/nightly/1?per_page=50&name_filter=Build%20Official%20Docker%20Images, which looks weird on HUD.

![Screenshot 2024-06-17 at 11 35 16](https://github.com/pytorch/test-infra/assets/475357/f0f980e0-2e39-4c90-b06f-75b7203dfe0a)

**Comment by clee2000** [comment]
Fixed by @atalman in https://github.com/pytorch/builder/pull/1874
