### ISSUE TITLE
Self-hosted runners for s390x for pytorch/pytorch repository get unregistered

### ISSUE THREAD

**Issue by AlekseiNikiforovIBM** [pytorch/test-infra#5384]
There were s390x runners registered to pytorch/pytorch repositories. Suddenly around 5th of June most of them or all of them got unregistered.

I've tried registering them again with help of @huydhn. First time part of runners was unregistered again on next day, while another part remained registered. Second time all runners got unregistered between registering them and running them, which took something like 10 minutes.

I've registered runners using same setup to private copy of pytorch repository and I'm not getting runners unregistered there.

s390x runners run in docker, and after each job they are restarted. While that's done, they appear offline for some time, but after initialization they connect to github again.

Is it possible that there's some cron job checking and unregistering offline runners? That would explain sometimes unregistering only some runners, and eventually unregistering all of them, and how it doesn't happen on a copy of repository.

Could you help me with investigating this issue? If you need access to s390x machines with runners, send me a message at pytorch slack.

PRs with updates for current setup of s390x runners:
https://github.com/pytorch/builder/pull/1900
https://github.com/pytorch/pytorch/pull/129866

**Comment by huydhn** [comment]
@jeanschmidt @seemethere @ZainRizvi  Do you know if there is any problems with the above setup that @AlekseiNikiforovIBM describes where the runner process itself it runs in a Docker container?  This could be an interesting case study for refreshable infra what we plan to build.  Maybe GH runner is not supposed to be restarted all the time using the same token or the token is single use only?

**Comment by AlekseiNikiforovIBM** [comment]
> Maybe GH runner is not supposed to be restarted all the time using the same token or the token is single use only?

Provided token is only used when registering GH runner like described and done here:
https://github.com/pytorch/pytorch/blob/0812b19b077641e460debcb811930301a3966627/.github/scripts/s390x-ci/README.md?plain=1#L46-L53
https://github.com/pytorch/pytorch/blob/0812b19b077641e460debcb811930301a3966627/.github/scripts/s390x-ci/self-hosted-builder/actions-runner.Dockerfile#L66-L72

After registration, each registered GH runner gets it's own private data, some sort of key, for connecting to github and specified repository or organization. This key doesn't look single use only, and it looks like such key doesn't expire for other repositories, or at least it doesn't expire as fast as it does for pytorch repository.

**Comment by malfet** [comment]
@jeanschmidt does terraform have a logic of unregistering the runners it does not manage? 
Or perhaps it happened when we tried to invalidate all of the runners due to the outage

**Comment by malfet** [comment]
I've issued new token to @AlekseiNikiforovIBM , but looks like setup when runner shuts-down after running a single job is fragile and should be avoided. 

And to the best of my knowledge, there are no scripts that deregister all the runner, but we have a script that removes offline runners

**Comment by AlekseiNikiforovIBM** [comment]
With token provided by @malfet I've first registered 1 runner named "pytorch.s390x.runner.1" and labels "self-hosted" and "linux.s390x", and then ran it and it successfully connected to github.

After that I've also registered runners "pytorch.s390x.runner.2" - "pytorch.s390x.runner.10" and "pytorch.s390x.runner.11" - "pytorch.s390x.runner.20". After that I've successfully started runners "pytorch.s390x.runner.2" - "pytorch.s390x.runner.10". I've started remaining runners a bit later, and for now "pytorch.s390x.runner.11" and "pytorch.s390x.runner.12" already failed to connect to github.

I suspect that mentioned script removing offline runners can sometimes find s390x runners and remove them, while s390x runners go offline for some time between registering and running, or after running jobs. It would be great if that script could exclude s390x runners, preferrably by label "linux.s390x", or by name.

**Comment by jeanschmidt** [comment]
Hi @AlekseiNikiforovIBM 

Indeed there [is a cron job](https://github.com/pytorch/test-infra/blob/main/terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts#L190) that runs every 15min and removes all offline runners registered in pytorch organization.

I believe the most correct approach is not 'skip' those runners in the cleaning sweep, but instead make them able to register themselves, as we do in all other UCs that we have. This is a more sound approach, as we guarantee a more clean state and avoid adding unnecessary maintenance burden into keeping track of the live and outdated runners that all our partners have.

Are you able to create a Github App that is within your control and request only the necessary permissions to register runners within an organization? If so we can install this app in Pytorch organization and so with your private key, you'll be able to authenticate to github and generate a key every time you need to fire a new runner.

**Comment by malfet** [comment]
@jeanschmidt do you mind posting link to the script here? Also, have we moved say rocm runners thru the app registration process? If not (i.e. there are no end-to-end working example) I'm ok with adding temporary exclusion of those labels, with the explicit understanding, that thru the app registration will be done in some reasonable time

**Comment by jeanschmidt** [comment]
@malfet link is [in my comment](https://github.com/pytorch/test-infra/issues/5384#issuecomment-2255767072)

I don't know the answer to this particular question, something that maybe @AlekseiNikiforovIBM can help answering.

But probably these runners are quite new ones, as this behaviour is present for a *very* long while (maybe ever?). In this case maybe makes more sense to go directly to the best solution.

But I have no opposition to implement a temporary solution if we agree and follow up to a final solution in a reasonable amount of time.

**Comment by AlekseiNikiforovIBM** [comment]
@jeanschmidt , I can register runners as ephemeral on each docker start, if I'm provided a different kind of key, a token for repository or organization which would allow only registering runners. Sorry, I've never made github apps before and I'd need to study it first if that's the way you want to use.

I've checked github documentation and found only organization-wine tokens for managing self-hosted runners:

https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-a-registration-token-for-an-organization
https://docs.github.com/en/rest/authentication/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#organization-permissions-for-self-hosted-runners

**Comment by jeanschmidt** [comment]
what github apps are, in simple terms, is a way to authenticate to github API.

You as a application owner, specify what permissions you want/need and register a github app requesting them. Then we as admin of pytorch org, installs it in our organization, what it does is allow you, when authenticate with your keys to access those permissions.

In this case to register runners :) 

I can guide you on this process if you need.

**Comment by jeanschmidt** [comment]
but the link you shared is correct. Then you follow the authentication as linked on [GitHub App installation access tokens](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app)

**Comment by AlekseiNikiforovIBM** [comment]
I'm willing to try out this github app approach. Your guidance is very appreciated.

**Comment by jeanschmidt** [comment]
The advantage is doing it in the way that enable you to maintain control, including listing and monitoring your instances if you want, and as your needs evolve there is a simple process to request and approve additional permissions.

Also, in case of security problems, it gets fairly easy to isolate any particular offending instance. Plus, as the authentication is private key based, any particular token that is leaked should not affect other runners, given each runner have its own unique key.

**Comment by jeanschmidt** [comment]
Installed the app, your installation ID is 53355289

**Comment by AlekseiNikiforovIBM** [comment]
Thanks, I've successfully re-registered s390x runners for pytorch org.

**Comment by AlekseiNikiforovIBM** [comment]
@malfet @huydhn , could you please re-enable nightly binaries build? I'd like to verify that current setup works. I also suspect that for nightly binaries s390x build https://github.com/pytorch/pytorch/pull/132484 would be needed.

**Comment by AlekseiNikiforovIBM** [comment]
It works as expected now with workers registering each time as ephemeral workers for one job right before starting worker. Closing as resolved. Thank you for help!
