### ISSUE TITLE
DrCI never updates job statuses

### ISSUE THREAD

**Issue by malfet** [pytorch/test-infra#5556]
We used to have periodic job that checked statuses of all pending jobs, but looks like it no longer works. I.e. have a look at DrCI report for https://github.com/pytorch/pytorch/pull/133519
<img width="1037" alt="image" src="https://github.com/user-attachments/assets/06914201-2047-45ae-945b-e3729122a0d1">
That in reality have 23 failed jobs , see https://github.com/pytorch/pytorch/pull/133519/commits/0026a9b2324e8c68d5d5d30ace6cb9e9612d2360 (Here is the link to the 1st attempt: https://github.com/pytorch/pytorch/actions/runs/10396146191/attempts/1 )but those failures happened during the outage, so webhooks were obviously lost, but DrCI should updated the status via this periodic job, shouldn't it? And re-run flaky failures?

**Comment by clee2000** [comment]
https://github.com/pytorch/test-infra/pull/5699 makes Dr. CI update comments that say pending
