### ISSUE TITLE
Log classifier crashes due to llm min_context_padding assert

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#5613]
From https://github.com/pytorch/test-infra/pull/5611#issuecomment-2319180491

With the example job id 29441399677, the log classifier crashes with the following error:

```
thread 'main' panicked at src/engine.rs:103:9:
min_context_padding cannot be greater or equal to half of max_chunk_size
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR lambda_runtime: Any { .. }
```

cc @PaliC @izaitsevfb @ZainRizvi

**Comment by huydhn** [comment]
This is probably a high priority item because of how Dr.CI works.  Till date, the log classifier rarely fails because of the lack of development works there (only when there is infra outage), so Dr.CI assumes that a failing log classifier signifies flaky infra issue, i.e. lambda fails to trigger, network outage.

**Comment by PaliC** [comment]
https://github.com/pytorch/test-infra/pull/5614 should fix this issue
