### ISSUE TITLE
Close merged PyTorch PRs that are still open

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#5627]
This happens from time to time due to GitHub outage where a PyTorch PR is merged but left open.  We usually just tell people to close it manually, i.e.

* https://github.com/pytorch/pytorch/pull/134795
* https://github.com/pytorch/pytorch/pull/134832

As this is not the first time the issue happens and it's confusing to devs, we should write a periodic job or an ad-hoc script to close all merged PyTorch PRs that are still open

cc @ZainRizvi @clee2000

**Comment by malfet** [comment]
Another example: https://github.com/pytorch/pytorch/pull/135620

**Comment by clee2000** [comment]
Not the solution mentioned in the issue body (periodic job) but https://github.com/pytorch/pytorch/pull/135890 makes mergebot close PRs that get merged
