### ISSUE TITLE
Dashboard makes all the old commits for a given week show the same date

### ISSUE THREAD

**Issue by eellison** [pytorch/test-infra#5696]
See:

<img width="192" alt="image" src="https://github.com/user-attachments/assets/22d0bb08-b5ab-48ff-abed-4700e51c9a9a">

I'm not sure why this is exactly but it makes it a little annoying to find the base commit for an old branch. cc @huydhn

**Comment by huydhn** [comment]
Taking a look

**Comment by huydhn** [comment]
I wonder if there was an infra issue during that week and all of the records were re-imported in the same date.  For this case, let me update them manually then

**Comment by eellison** [comment]
@huydhn for me it happens for all old commits, not just that week. see:

<img width="1406" alt="image" src="https://github.com/user-attachments/assets/44c03bcb-10b9-4246-b429-ccf185addc55">

**Comment by huydhn** [comment]
Oh, you're right, it shows up when last quarter is selected, I suspect that this might has something to do with https://github.com/pytorch/test-infra/issues/4123

**Comment by huydhn** [comment]
I have the fix here https://github.com/pytorch/test-infra/pull/5725
