### ISSUE TITLE
Check labels job is not retriggered when label is added

### ISSUE THREAD

**Issue by ezyang** [pytorch/test-infra#5764]
Self explanatory, and easy to reproduce.

**Comment by malfet** [comment]
Can you give an example PR here, as it should have been, according to 
https://github.com/pytorch/pytorch/blob/4abe38bc9483ebfcd73e8ed4af645a655ca4a9b4/.github/workflows/check-labels.yml#L10
and 
https://github.com/pytorch/pytorch/blob/4abe38bc9483ebfcd73e8ed4af645a655ca4a9b4/.github/workflows/check-labels.yml#L18

**Comment by ezyang** [comment]
this PR https://github.com/pytorch/pytorch/pull/137924

**Comment by kit1980** [comment]
Maybe it was some kind of temporary Github issue.

**Comment by huydhn** [comment]
Confirm with @kit1980 and @ezyang that the issue is working now.  Please re-open if this happens again.
