### ISSUE TITLE
[ciflow] ciflow bot doesn't allow for application for labels for approved PRs

### ISSUE THREAD

**Issue by seemethere** [pytorch/test-infra#5900]
Looks like ciflow is running into an issue where it thinks it's not allowed to apply labels when it should be.

https://github.com/pytorch/pytorch/pull/139760#issuecomment-2470965127

![Screenshot 2024-11-12 at 8 19 13 AM](https://github.com/user-attachments/assets/1288949f-3695-47ec-844c-27b0619ad5bc)

**Comment by ZainRizvi** [comment]
Turns out this is by design (it wants you to first approve running the regular pull workflow) but the error message has room for improvement.

PR to improve the message: https://github.com/pytorch/test-infra/pull/6088
