### ISSUE TITLE
Organize artifacts by jobs

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#609]
### Pitch

At the moment, we list the status of the job before all the S3 artifacts, for example https://hud.pytorch.org/pytorch/pytorch/commit/ff23f3ac1c10f6bd5104f27aa1566b71e2ae6fa0.  So the structure looks like this:

```
Workflows
pull
Job status
  0 Job A
    Error if any
  0 Job B
  X Job X
    Error
Artifacts
  [s3] Sorted alphabetically
```

IMO, this is not ideal because I always need to scroll back and forth to find all the artifacts associated with a failed job.  It would be much easier to find stuffs if they are grouped by jobs.  So the proposed layout looks as follows:

```
Workflows
pull
Job status
  0 Job A
    Error if any
    > collapsible Artifacts from A
  0 Job B
    > collapsible Artifacts from B
  X Job X
    Error
    > collapsible Artifacts from C
```

or 

```
Workflows
pull
Job status
  0 Job A [link to A artifacts]
    Error if any
  0 Job B [link to B artifacts]
  X Job X [link to C artifacts]
    Error
```

I also notice that there are one or two artifacts like `.pytorch-test-times.json` which link with the whole workflow instead of individual job.  However, there are only few of them.  So it's ok to list them separately at the end I think.

Thoughts?

cc @ZainRizvi @suo @pytorch/pytorch-dev-infra

**Comment by ZainRizvi** [comment]
It sounds reasonable in general, though I'd be concerned about not making the input too noisy for users.  I'll defer to others on how often folks actually look at the artifacts (I haven't explored them yet myself), but I suspect it's a relatively rare thing.

A couple ideas:
- Keep the artifacts at the bottom as is, but for **failed** jobs only, also link to the artifacts directly below the job (as suggested)
- Place the artifacts for each job in some expandable section so that they're usually hidden from view

**Comment by seemethere** [comment]
Artifacts are generally useful imo since they allow for some level of local reproduction.

That being said I do think they should be hidden behind a click through.

**Comment by suo** [comment]
Agree with folks above. I think artifacts are useful in specific contexts (esp. for dev infra), but I think the majority of PyTorch contributors do not look at them/know what they are. Honestly even the current display which takes up a lot of vertical space for the artifacts is probably too noisy.

So if we can put them inline but in an unobtrusive way, it would be best.

**Comment by huydhn** [comment]
Yeah, I think we can group artifacts by job with an expandable to hide them from view.  Note that the artifacts doesn't need to be right under the job status. A click away pointing to an anchor will do fine.  That way we can hide the whole artifact section if need to

**Comment by suo** [comment]
I think listing artifacts inline is a good idea for ease of access.

One downside is that it makes the job listing less readable. Most
contributors don’t use/care about artifacts and just want to see jobs and
failures.

Can we make the inline artifact link more unobtrusive some how?

**Comment by clee2000** [comment]
I think most of this is completed by #4664
