### ISSUE TITLE
DrCI does not post any updates

### ISSUE THREAD

**Issue by malfet** [pytorch/test-infra#6106]
May be I was block-listed, but I doubt it, see https://github.com/pytorch/pytorch/pull/143763#issuecomment-2560147568 <- no edits on the comment even though PR were created an hour ago and one edit after `@pytorchbot drci` command were issued

**Comment by malfet** [comment]
And looks like https://github.com/pytorch/test-infra/actions/workflows/update-drci-comments.yml has been failing for the last 3-4 days

**Comment by huydhn** [comment]
The code fails to handle this PR https://github.com/pytorch/pytorch/pull/143615.  Let's see what happens there
