### ISSUE TITLE
Disable test button doesn't work for pytest failures

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#788]
I just notice that the disable test button on HUD doesn't work for parallelized tests.  Here are some example 

* https://hud.pytorch.org/pytorch/pytorch/commit/a0be0ca16144fababbbb94f58b1fd88e41f29162
* https://hud.pytorch.org/pytorch/pytorch/commit/686555b663077b40f28bc88adc049e64035046b4

The filter correctly matches against `=================================== FAILURES ===================================`, which is fine.  However, the failed test `TestOperatorsCUDA.test_vjpvjp_matrix_exp_cuda_float32` is on the next line and this probably breaks this feature.

cc @clee2000 @ZainRizvi @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
Some additional examples with one ROCM flaky test
* https://hud.pytorch.org/pytorch/pytorch/commit/f325c29b05fdf350322dcb26e2cd6dff3fb06f1e
* https://hud.pytorch.org/pytorch/pytorch/commit/12ae3bea437e760d4fede3f1c50c2c81af3f687c

**Comment by ZainRizvi** [comment]
By "parallelized tests" do you mean the tests we just started parallelizing, or are these tests that already ran in parallel?

**Comment by huydhn** [comment]
> By "parallelized tests" do you mean the tests we just started parallelizing, or are these tests that already ran in parallel?

My guess is the latter, I realize that this is the way pytest outputs its results https://github.com/pytorch/test-infra/blob/main/torchci/pages/api/classifier/rules.ts#L108-L110 (and we use pytest to run stuff in parallel, thus the impresion).  Let me update the title to make it clearer

**Comment by huydhn** [comment]
Not related but here is an example of a ticket to disable pytest test manually https://github.com/pytorch/pytorch/issues/85755. Notice that the test case name from pytest `TestOperatorsCUDA.test_vjpvjp_matrix_exp_cuda_float32` now becomes `test_vjpvjp_matrix_exp_cuda_float32 (__main__.TestOperatorsCUDA)` in the title
