### ISSUE TITLE
DrCI comment is out of date for https://github.com/pytorch/pytorch/pull/85524

### ISSUE THREAD

**Issue by malfet** [pytorch/test-infra#791]
More that 16 hours after https://github.com/pytorch/pytorch/pull/85524/commits/9e8303243e3f43ca85329012c16a3d2566d85f82 was pushed (and more than 10 after all runs have finished)
DrCI comment https://github.com/pytorch/pytorch/pull/85524#issuecomment-1255685960 fails to update (can't post a link to a comment version, so sharing a screenshot)
<img width="862" alt="image" src="https://user-images.githubusercontent.com/2453524/192573010-818961f3-c65c-48f6-b3ee-989ca72a91ea.png">

**Comment by ZainRizvi** [comment]
Closing as a dupe of https://github.com/pytorch/pytorch/issues/87868
