### ISSUE TITLE
Move stats/disabled-tests.json to S3

### ISSUE THREAD

**Issue by janeyx99** [pytorch/test-infra#93]
The disabled tests json is updated through a GHA workflow that runs every 15 min. This causes many commits to the test-infra repo, which adds unnecessary noise + bloats our commit history.

We could remedy this by:
1. Hosting the disabled tests elsewhere, like on S3. This would effectively remove the noise in our commit history, but we would lose the previous benefits of having it on a GitHub repo. For example, it would be harder to modify and update the file manually, and there would be no review process when that occurs. Secondly, version control would be harder to visualize for an S3 bucket compared to with Git, which is a system built for versioning.

2. Looking back on a few commits, such as https://github.com/pytorch/test-infra/commit/d18b4175140abbc6f140a8c3d00427f438b503f2, it seems as if the contents for the disabled tests have not actually changed, but it's been the order of the json arrays. If there's an easy way to sort the json before we commit, we could also reduce noise by only making commits when the actual contents change. 

Please comment which alternative you think is better!

**Comment by samestep** [comment]
What about trying (2) now, seeing how much it reduces the noise, and then doing (1) if we still want to reduce the noise further?
