### ISSUE TITLE
The flaky test bot is not marking issues as "triaged" properly

### ISSUE THREAD

**Issue by albanD** [pytorch/test-infra#934]
Any any module beyond `module: unknow` is set, it should also mark the issue as `triaged`.
This is not happening right now for modules like functorch/decompositions at least.

**Comment by clee2000** [comment]
if it gets `module: flaky-tests` but also `module: unknown`, should it get `triaged`?

also, do you have any examples? im wondering if the reason some of them didnt get `triaged` label but got `module: decomposition` is because i added some manually

**Comment by albanD** [comment]
I think it is: if there are any other `module: *` appart from `flaky-tests` or `unknown`, then it should be marked `triaged`.

**Comment by kit1980** [comment]
Closing this for now, please reopen if re-occurs.
